// Eldar Intelligence Hub — Daily Data
// Auto-updated: 14:29 04.05.2026 IST
// Generated by Sofia v11 — Real Data Only, GPT for Insights Only
export interface NewsItem {
  id: number;
  type: "news" | "content";
  category: string;
  title: string;
  summary: string;
  whyItMatters: string;
  implications: string;
  importance: number;
  sourceUrl: string;
  sourceName: string;
  authorName?: string;
}

export interface Trend {
  title: string;
  description: string;
  direction: "up" | "down" | "stable";
}

export interface MarketIndex {
  name: string;
  value: string;
  change: string;
  direction: "up" | "down" | "stable";
}

export interface MarketData {
  date: string;
  indices: MarketIndex[];
  currencies: MarketIndex[];
  commodities: MarketIndex[];
  israelHeadlines: string[];
  wallStreetHeadlines: string[];
  watchTomorrow: string;
}

export const NEWS_DATE = "04.05.2026";

export const LAST_UPDATED = "14:29 04.05.2026";

export const REPORT = {
  date: NEWS_DATE,
  breakingItems: ["📈 הבורסה בשיאים; נייס מזנקת בכ-19%, השקל נחלש", "🏛️ אזעקות בגליל המערבי בשל ירי מלבנון - וואלה חדשות", "⚔️ שיקום שיניים מתקדם: מה אפשר לתקן היום - ובאיזו מהירות - וואל", "👥 האח של יוסי ואלי שרעבי מצטרף לליברמן, מייסדת \"בונות אלטרנטיב", "🤖 האוסקר קובע: שחקנים ותסריטי AI מחוץ לתחרות - גיקטיים"],
  executiveSummary: "היום מתאפיין בשילוב של מתחים ביטחוניים בצפון ישראל לצד הזדמנויות כלכליות בשוק ההון ובתחום הטכנולוגיה. השקעות בטכנולוגיות הגנה מתקדמות ובינה מלאכותית מתמודדות עם אתגרים חדשים, בעוד שינויים במנהיגות ובשיתופי פעולה עסקיים מצביעים על דינמיות בשוק המקומי. יש להמשיך לעקוב אחרי ההתפתחויות הביטחוניות והכלכליות כדי למקסם הזדמנויות ולהפחית סיכונים.",
  conclusion: "המציאות המשתנה מחייבת מנהלים להיות ערניים ולהתאים את האסטרטגיות העסקיות בהתאם למגמות הביטחוניות והטכנולוגיות.",
  watchNext24h: "יש לעקוב אחרי התפתחויות ביטחוניות בצפון ותגובות השווקים הגלובליים למתחים במזרח התיכון.",
};

export const NEWS_ITEMS: NewsItem[] = [
  { id: 1, type: "news", category: "כלכלה", title: "הבורסה בשיאים; נייס מזנקת בכ-19%, השקל נחלש", summary: "המסחר בתל אביב מתנהל הבוקר על רקע המגמה החיובית בעולם - גופים מוסדיים מובילים רוכשים מקרן פורטיסימו מניות סוגת בכ-430 מיליון שקל - תורפז עולה לאחר שהודיעה על רכישת חברת תמציות ריח בתחום הבישום", whyItMatters: "עלייה בשווי הבורסה ובמניית נייס משקפת אמון המשקיעים בטכנולוגיה הישראלית, אך השקל החלש יכול להשפיע על ייבוא ועל מחירי הצריכה.", implications: "יש לעקוב אחרי השפעת התחלופה בשקל על עלויות הייצוא והייבוא, במיוחד לחברות טכנולוגיה ותעשייה.", importance: 7, sourceUrl: "https://www.globes.co.il/news/article.aspx?did=1001541788#utm_source=RSS", sourceName: "גלובס" },
  { id: 2, type: "news", category: "כלכלה", title: "עקב הדיווח האיראני על תקיפת ספינה אמריקאית: ירידות בחוזים העתידיים על וול סטריט", summary: "החוזים העתידיים על וול סטריט עברו לירידות, בעקבות דיווח איראני על שיגור שני טילים לעבר ספינה אמריקאית בהורמוז - מחירי הנפט מזנקים, נפט מסוג ברנט נע סביב 114 דולר לחבית - מוקדם יותר, טראמפ", whyItMatters: "הדיווח האיראני על תקיפת ספינה אמריקאית מעלה חששות גיאופוליטיים שמשפיעים על השווקים העולמיים ועל יציבות ההשקעות.", implications: "ייתכן ירידות בשוקי ההון ובחוזים העתידיים, ויש לעקוב אחרי תגובות נוספות במזרח התיכון.", importance: 7, sourceUrl: "https://www.globes.co.il/news/article.aspx?did=1001541840#utm_source=RSS", sourceName: "גלובס" },
  { id: 3, type: "news", category: "פוליטיקה", title: "אזעקות בגליל המערבי בשל ירי מלבנון - וואלה חדשות", summary: "אזעקות בגליל המערבי בשל ירי מלבנון וואלה חדשות", whyItMatters: "ירי מלבנון באזור הגליל המערבי מדגיש את המתיחות הביטחונית באזור הצפוני, המשפיעה על תחושת הביטחון והפעילות הכלכלית.", implications: "עסקים באזור ובתחום התיירות צריכים להתכונן להשפעות אפשריות על פעילותם ולקשיים לוגיסטיים.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMiT0FVX3lxTE5aQl9ram9JcDIzMXZEbVM5S2lNMlNjNXE1M1JKRnhGQmhPaW1jQWFrVUtsS2RjZExOM3g3U2YtMk9YbDlvckRFSVBRbExxd00?oc=5", sourceName: "וואלה חדשות" },
  { id: 4, type: "news", category: "פוליטיקה", title: "גבר כבן 50 נפצע באורח קשה מדקירות בחיפה - וואלה חדשות", summary: "גבר כבן 50 נפצע באורח קשה מדקירות בחיפה וואלה חדשות", whyItMatters: "פציעה קשה כתוצאה מאלימות בחיפה מצביעה על אתגרי ביטחון פנים שיכולים להשפיע על האקלים העסקי והחברתי בעיר.", implications: "יש לשים לב להשפעות ארוכות טווח על תדמית העיר ועל היציבות החברתית באזור.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMiT0FVX3lxTE5ndkdXQmdVR09NZUtWUzNsN2tfdmR6UzJqZFM0YU5aaGZIaktoaG54TmpZZzF0bGhiMGlfanVhWlF1WEM2YmpCNTJrMUZYMGc?oc=5", sourceName: "וואלה חדשות" },
  { id: 5, type: "news", category: "צבא וביטחון", title: "שיקום שיניים מתקדם: מה אפשר לתקן היום - ובאיזו מהירות - וואלה בריאות", summary: "שיקום שיניים מתקדם: מה אפשר לתקן היום - ובאיזו מהירות וואלה בריאות", whyItMatters: "התקדמות בשיקום שיניים מציעה פתרונות רפואיים מהירים ויעילים, המשפרים את איכות החיים ויכולים להשפיע על תחום הבריאות הפרטי והציבורי.", implications: "חברות בתחום הרפואה והבריאות יכולות לנצל את הטכנולוגיות החדשות להרחבת שירותיהן.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMiUkFVX3lxTE5LdndXa2FZMFR1Q2dadUZZUHNPTzVNamJweFRKcGVWbjdaX1JIQUY5eW5pUEd0WGFVcWFQa1p3MjB2UmR2QVh4OHdwUGxZUmFhYlE?oc=5", sourceName: "וואלה בריאות" },
  { id: 6, type: "news", category: "צבא וביטחון", title: "IDF Deploys New Drone Interception System as Hezbollah Expands FPV Threat - Israel Defense", summary: "IDF Deploys New Drone Interception System as Hezbollah Expands FPV Threat Israel Defense", whyItMatters: "הטמעת מערכת יירוט רחפנים חדשה בצה״ל משקפת התמודדות עם איומי טרור מתקדמים מצד חיזבאללה, ומחזקת את ההגנה הביטחונית.", implications: "ההשקעה בטכנולוגיות הגנה מתקדמות עשויה להשפיע על תקציבי הביטחון והחדשנות הטכנולוגית בישראל.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMiWEFVX3lxTE1paFNzNUFWUHMyQW00VXdWQ2d4bkVRdklNNWlsVTRYVFVOUFJxbUk1OTlwYS1xRmt0al9BeklTVUtacm1qcHNMcjQxcWYwSGZuY1FZNTg5VlU?oc=5", sourceName: "Israel Defense" },
  { id: 7, type: "news", category: "חברה", title: "האח של יוסי ואלי שרעבי מצטרף לליברמן, מייסדת \"בונות אלטרנטיבה\" - ליאיר גולן", summary: "מפלגות האופוזיציה מעלות הילוך לקראת בחירות 2026 ומודיעות על שמות חדשים. שרון שרעבי, מהקולות הבולטים להשבת החטופים: \"'הליכוד של פעם' זו ישראל ביתנו\". מורן זר קצנשטיין, שנמנית עם מובילות מאבק הנשים, מסר", whyItMatters: "הצטרפות דמות חברתית מוכרת לליברמן מצביעה על שינויים במפה הפוליטית והחברתית, שעשויים להשפיע על מדיניות ויציבות הממשלה.", implications: "יש לעקוב אחרי השפעות פוליטיות אפשריות על תחומי כלכלה וחברה בעקבות שינויים אלו.", importance: 7, sourceUrl: "https://www.ynet.co.il/news/article/s1md1rhrzg", sourceName: "ynet" },
  { id: 8, type: "news", category: "חברה", title: "ונדליזם אנטי-ישראלי בהולנד: \"דם\" וכתובת \"ג'נוסייד\" על האנדרטה באמסטרדם", summary: "האנדרטה הלאומית בכיכר דאם רוססה ביום הזיכרון הלאומי לחללי המלחמה, ראש העיר: \"מעשה פחדני שפוגע במשפחות של קורבנות מלחמת העולם השנייה\". בשנה שעברה הושחתה האנדרטה עי פרו-פלסטינים, ובסמוך לה נכתב Fuck Is", whyItMatters: "ונדליזם אנטי-ישראלי בהולנד מדגים את המשך המתח והקונפליקטים סביב ישראל גם בזירה הבינלאומית, המשפיעים על תדמית המדינה בעולם.", implications: "יש להיערך להגברת פעילות דיפלומטית ותקשורתית לשיפור התדמית והגנה על האינטרסים בישראל בחו״ל.", importance: 7, sourceUrl: "https://www.ynet.co.il/news/article/ry9lxx8cbe", sourceName: "ynet" },
  { id: 9, type: "news", category: "טכנולוגיה", title: "האוסקר קובע: שחקנים ותסריטי AI מחוץ לתחרות - גיקטיים", summary: "האוסקר קובע: שחקנים ותסריטי AI מחוץ לתחרות גיקטיים", whyItMatters: "החלטת האוסקר לא לאפשר שחקנים ותסריטים מבוססי בינה מלאכותית משקפת את החששות האתיים והמקצועיים בתחום הבידור והטכנולוגיה.", implications: "חברות הפקה וטכנולוגיה יצטרכו להגדיר גבולות ברורים לשימוש בבינה מלאכותית בתוכן יצירתי.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMif0FVX3lxTFBtM0JuYWwyVW5GX1Y3TV9vc2t0X3R5NHlZeVY1SWo0UmpyRWRDdTdSN2pvYmtlcVZFdXppd0kyVm5EN2s0TzRWcEZRdFgwSzhQLUNQVkowQ1JybnBEZzJGYzl0UUNuSTJYdTBJTVpmRktEZXNrWmdJNk1uZnYzTlk?oc=5", sourceName: "גיקטיים" },
  { id: 10, type: "news", category: "טכנולוגיה", title: "לא רק AI: כנס Geektime Code מחפש דוברות ודוברים עם הרצאות מעולות - גיקטיים", summary: "לא רק AI: כנס Geektime Code מחפש דוברות ודוברים עם הרצאות מעולות גיקטיים", whyItMatters: "כנס Geektime Code מדגיש את החשיבות ההולכת וגדלה של חדשנות טכנולוגית ותקשורת מקצועית בישראל.", implications: "הזדמנות לחברות ולמפתחים להציג חידושים וליצור שיתופי פעולה משמעותיים.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMiaEFVX3lxTE52bjZkM1ZyLXVudVhvY0pLVjZWTzd5VkJCdDh2Mk82YmVDRlB4WVZ4a1VjWV84RkZOcUhqSHdIc0NFUU5MaVF6bjZmSFFMNU5JdHRkOXlha3B3R2huZjVuZEp5NVZTRUlo?oc=5", sourceName: "גיקטיים" },
  { id: 11, type: "news", category: "אירועים", title: "Tower Semiconductor maps out four investor conferences in May and June - Stock Titan", summary: "Tower Semiconductor maps out four investor conferences in May and June Stock Titan", whyItMatters: "תכנון כנסים למשקיעים של Tower Semiconductor מעיד על רצון החברה להרחיב את בסיס המשקיעים ולגייס הון להמשך פיתוח.", implications: "משקיעים צריכים לעקוב אחרי הצגת התוכניות וההזדמנויות להשקעה בחברה.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMitAFBVV95cUxPaFZkbU10S1JZRzZpSFlKZEFfeC0zY3hYR0sxNjF6cjlSbjYyaTU0Zy04UGZQdGJpTEFob1ZUQzcxQU02VmFsMnVDbVc0dVhZaXJUc25MVGNJX044bkJLRW1abmNDcUtQZHlpcnJMWHRyNXdwOE5JWEFJemVjdDVYV19GMFpwSm51T2hDVnpNWXZ2RG9HTHFMVEhiMEszLTQwQnVIRnRjNmU3YkNscWdpU1REcWE?oc=5", sourceName: "Stock Titan" },
  { id: 12, type: "news", category: "אירועים", title: "Tower Semiconductor (TSEM) plans investor conference meetings in May and June - Stock Titan", summary: "Tower Semiconductor (TSEM) plans investor conference meetings in May and June Stock Titan", whyItMatters: "הכנות לפגישות עם משקיעים מחזקות את מעמדה של Tower Semiconductor בשוק ההון ומאפשרות שקיפות מול המשקיעים.", implications: "ייתכן גיוס הון או עדכונים חשובים שישפיעו על מחיר המניה.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMiuwFBVV95cUxOUHlIanFZdXJvODVwaVZwazJtbW5JTHc1SkhxMTdEdWRua1pPVDJmTFRuMjJyRkhkemZycWoxLWlnUXVwT0JQcnVUeGZMMmdWTjZOQ3haVktlUG9oMFAzWmpMQ1lTd3RBblFPaEZoWVE3Q3BuVkU1VHNRODZobnZrT3JYV1JJdkpwa0ZWZUlLZUJCcGZJNFlwOEZHTzNIZjNVRjVHQkNNby1rMlZORDNEeGpKY2JCeThBNklF?oc=5", sourceName: "Stock Titan" },
  { id: 13, type: "news", category: "בידור", title: "Apple TV’s New 100% Rt Horror Series Is Officially Taking Over the World - IMDb", summary: "Apple TV’s New 100% Rt Horror Series Is Officially Taking Over the World IMDb", whyItMatters: "הצלחה עולמית של סדרת אימה ב-Apple TV מדגימה את הפוטנציאל של תכנים ישראליים או בעלי קשר לישראל בשוק הבידור הגלובלי.", implications: "הזדמנות לחברות הפקה ישראליות להרחיב את השפעתן בשווקים בינלאומיים.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMiZ0FVX3lxTE5VRjk0TjdZcWRsa3dJc0NrVTFnSGhyajg5NnhmVmRXQ0xHOUdyVEFVV09YalpIZVRWRnRaVGNLeUdZYU5hdDFlZVZ1VGJZQnNvdDZfQWFQUTNBWEcxU1F6aGQtYnVmN1k?oc=5", sourceName: "IMDb" },
  { id: 14, type: "news", category: "בידור", title: "לקראת הוועידה הכללית של פתח – ביקורת על עבאס בשל כוונתו לקדם את בנו - אפוק", summary: "לקראת הוועידה הכללית של פתח – ביקורת על עבאס בשל כוונתו לקדם את בנו אפוק", whyItMatters: "ביקורת פנימית בפת״ח על קידום בני משפחה מצביעה על בעיות בשקיפות ובהנהגה שיכולות להשפיע על יציבות האזורית.", implications: "המשך מתחים פוליטיים עשוי להשפיע על תהליכים מדיניים ועסקיים באזור.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMiSEFVX3lxTE45NjJWeWJSa29ucncxNXNKZ1FsNmd5dkF4QS1DRkVDN2RETGkwNHhOVWpubWQtcWstYk5KV2xPREoxclJDd2J0bg?oc=5", sourceName: "אפוק" },
  { id: 15, type: "news", category: "פיתוח אישי", title: "גרג ברוקמן: 72 השעות שיכלו כמעט להרוג את OpenAI", summary: "מרוץ הבינה המלאכותית, עתיד ה-AGI, והסיפור הפנימי של OpenAI. גרג ברוקמן הוא מייסד שותף ונשיא OpenAI, החברה שמאחורי ChatGPT ו-GPT-5. הוא היה המהנדס הראשון ב-Stripe לפני כן.", whyItMatters: "סיפורו של גרג ברוקמן על משבר ב-OpenAI מראה את האתגרים הגדולים בניהול חברות טכנולוגיה מתקדמות בעולם התחרותי.", implications: "חברות ישראליות בתחום הבינה המלאכותית יכולות ללמוד מהניסיון ולהיערך טוב יותר למשברים דומים.", importance: 7, sourceUrl: "https://fs.blog/knowledge-project-podcast/greg-brockman/", sourceName: "Farnam Street" },
  { id: 16, type: "news", category: "פיתוח אישי", title: "מריו האריק: לשחק כדי לנצח", summary: "מריו האריק הוא מנהל כללי XPO, אחת מחברות הלוגיסטיקה הגדולות בעולם. במשך שנים היה protegee של היזם האגדי ברד ג'ייקובס, שבנה שמונה חברות במיליארדי דולרים.", whyItMatters: "הגישה של מריו האריק לשחק כדי לנצח מדגישה את החשיבות של חשיבה יצירתית ואסטרטגית בפיתוח אישי ועסקי.", implications: "מנהלים ואנשי עסקים יכולים לאמץ גישות חדשניות לשיפור ביצועים והובלת צוותים.", importance: 7, sourceUrl: "https://fs.blog/knowledge-project-podcast/mario-harik/", sourceName: "Farnam Street" }
];

export const CONTENT_ITEMS: NewsItem[] = [
  { id: 100, type: "content", category: "טכנולוגיה", title: "לא רק AI: כנס Geektime Code מחפש דוברות ודוברים עם הרצאות מעולות - גיקטיים", summary: "לא רק AI: כנס Geektime Code מחפש דוברות ודוברים עם הרצאות מעולות גיקטיים", whyItMatters: "השפעה על תעשיית ההייטק והחדשנות", implications: "השפעה על תעשיית ההייטק והחדשנות", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMiaEFVX3lxTE52bjZkM1ZyLXVudVhvY0pLVjZWTzd5VkJCdDh2Mk82YmVDRlB4WVZ4a1VjWV84RkZOcUhqSHdIc0NFUU5MaVF6bjZmSFFMNU5JdHRkOXlha3B3R2huZjVuZEp5NVZTRUlo?oc=5", sourceName: "גיקטיים" },
  { id: 101, type: "content", category: "כלכלה", title: "יוסי אבו, מנהל כללי ניו מד, עוזב את תפקידו לאחר 15 שנה", summary: "אבו רמז על כוונותיו: \"חשבתי שהגיע הזמן בעבורי להמשיך במסע להזדמנויות חדשות בזירה הגלובאלית ולאתגרים נוספים\" - גולת הכותרת של פעילותו במשק הגז הישראלי הייתה הובלת הסכמי הייצוא האזורים החל משנת 20", whyItMatters: "השפעה אפשרית על שוק ההון ועל הכלכלה הישראלית", implications: "השפעה אפשרית על שוק ההון ועל הכלכלה הישראלית", importance: 6, sourceUrl: "https://www.globes.co.il/news/article.aspx?did=1001541859#utm_source=RSS", sourceName: "גלובס" },
  { id: 102, type: "content", category: "צבא וביטחון", title: "מאיפה יבוא הכסף? הממשלה אישרה עוד טייסות אף-35 ואף-15 - וואלה כסף", summary: "מאיפה יבוא הכסף? הממשלה אישרה עוד טייסות אף-35 ואף-15 וואלה כסף", whyItMatters: "השלכות ביטחוניות שיש לעקוב אחריהן", implications: "השלכות ביטחוניות שיש לעקוב אחריהן", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMiUkFVX3lxTE04aDBwTktsaG1BR2RJNFRFUTN0NFdYNUloZkFkbWpDdXFWVk9TSVk2VTJMSXo0M2VqRHBzZnEzdXdFb0JYRXJhOEdjM1E1WVIyVlE?oc=5", sourceName: "וואלה כסף" },
  { id: 103, type: "content", category: "חברה", title: "איראן פרסמה מפת \"אזורי שליטה\" בהורמוז וטוענת שפגעה במשחתת, ארצות הברית מכחישה", summary: "התחממות במפרץ, אחרי תחילת יישום \"פרויקט חופש הספינות\" של טראמפ. לפי האיראנים, שני טילים פגעו באזור מצר הורמוז בספינה שלא נענתה לאזהרות הצי האיראני. צבא ארצות הברית הכחיש: \"אף ספינה לא נפגעה\". מפקד סנטקום תו", whyItMatters: "נושא חברתי שמשפיע על השיח הציבורי", implications: "נושא חברתי שמשפיע על השיח הציבורי", importance: 6, sourceUrl: "https://www.ynet.co.il/news/article/h1ybbglcbg", sourceName: "ynet" }
];

export const TRENDS: Trend[] = [
  { title: "התגברות המתחים הביטחוניים בצפון ישראל", description: "ירי מלבנון והתגברות איומי רחפנים מצד חיזבאללה מחייבים השקעות בטכנולוגיות הגנה מתקדמות ושמירה על יציבות האזור.", direction: "up" },
  { title: "הרחבת השימוש בבינה מלאכותית עם אתגרים אתיים", description: "החלטות כמו זו של האוסקר מראות על הצורך באיזון בין חדשנות טכנולוגית לשמירה על ערכים מקצועיים ואתיים בתעשיית הבידור והטכנולוגיה.", direction: "up" },
  { title: "שינויים במנהיגות ובשיתופי פעולה עסקיים בישראל", description: "עזיבת מנהלים ותנועות פוליטיות לצד שיתופי פעולה חדשים בתחום התיירות והנדל״ן מעידים על דינמיות בשוק המקומי והבינלאומי.", direction: "up" }
];

export const WINE_NEWS: NewsItem[] = [

];

export const TOURISM_NEWS: NewsItem[] = [
  { id: 301, type: "news", category: "תיירות", title: "אחרי 24 שנים באל על: פיזיצקי מסיימת את תפקידה בחברת התעופה - PassportNews", summary: "אחרי 24 שנים באל על: פיזיצקי מסיימת את תפקידה בחברת התעופה PassportNews", whyItMatters: "עזיבתה של פיזיצקי מאל על לאחר 24 שנים מסמנת שינוי במנהיגות שיכול להשפיע על אסטרטגיית החברה ותפעולה.", implications: "יש לעקוב אחרי מינויי ההמשך והשפעתם על פעילות החברה בשוק התעופה.", importance: 7, sourceUrl: "https://news.google.com/rss/articles/CBMiU0FVX3lxTE9kbEhld2tyTUdXeHdjRVhyelUyNVhKM2IzWFRvUE45WHAzVnVHT1lqcVhXaUtlTXpqNzdDTzZ6eTRLQ1o1SVNPcVl3Qm1KaDBUWGtN?oc=5", sourceName: "PassportNews" },
  { id: 302, type: "news", category: "תיירות", title: "קונים דירה - מרוויחים טיסות: שיתוף פעולה חדש למועדון \"הנוסע המתמיד\" - PassportNews", summary: "קונים דירה - מרוויחים טיסות: שיתוף פעולה חדש למועדון \"הנוסע המתמיד\" PassportNews", whyItMatters: "שיתוף פעולה בין מועדון הנוסע המתמיד לבין שוק הנדל״ן מציע הזדמנויות ייחודיות ללקוחות ולחברות בתחום התיירות והנדל״ן.", implications: "עסקים בתחום התיירות והנדל״ן יכולים לנצל את המיזוג ליצירת ערך מוסף ללקוחות.", importance: 7, sourceUrl: "https://news.google.com/rss/articles/CBMiU0FVX3lxTFA3UjNKYmZZYjJjYlVoN2c2WXpDb1hEaGlrcnhMaHRYQW1GQVl2Z1FGUVYzQi1wQW9JLXljTVFGTmcyVnlXSnZUbTFKZzB6RjhzM0dV?oc=5", sourceName: "PassportNews" },
  { id: 303, type: "news", category: "תיירות", title: "Forget Flying This Summer: America's Road Trips Just Got Their Biggest Upgrade In Decades - TheTravel", summary: "Forget Flying This Summer: America's Road Trips Just Got Their Biggest Upgrade In Decades TheTravel", whyItMatters: "שדרוג דרכי הנסיעה בארצות הברית מעיד על שינוי בהרגלי התיירות ועל הזדמנויות לפיתוח תשתיות ועסקים בתחום התיירות הפנימית.", implications: "חברות תיירות ישראליות יכולות ללמוד מהשינויים ולהתאים את ההצעות ללקוחות בינלאומיים.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMihAFBVV95cUxQcHY0cEhfZUZoOEpudVcwVV9RQWRrVkQzMWctQ0hEUkZpNW1Wa1pndlktb3ZHUUFFU3pNaFdveG5aa2ZscVN4WHd4aE5GRk9lMnlXUDBPcTVWY01OclREM2tvNzdlSzYwdEtqS3FfWXBvN1RaQlRiOS1GUmtEN2RsTHdtTFo?oc=5", sourceName: "TheTravel" },
  { id: 304, type: "news", category: "תיירות", title: "5 Best International Beach Getaways for Couples This Summer - Herzindagi", summary: "5 Best International Beach Getaways for Couples This Summer Herzindagi", whyItMatters: "המלצות על חופשות חוף בינלאומיות לזוגות מצביעות על מגמת התחדשות בתיירות הרומנטית והפנאי העולמית.", implications: "עסקים בתחום התיירות בישראל יכולים להתמקד בקהלים זוגיים ולפתח חבילות תיירות ייחודיות.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMirAFBVV95cUxNd183S3dfZHhwdDJLTUY4eklQZ1R4NzhoYjRWVjVQUy1aQ1FXSWJwd05IT0xJMjB4bEJ3aGhmbUdSYnNZeVNrY2F4VEEteWJySU9NVE4wUTN6ajZPR0hWbjNlT1o2cXltQTRKaGtsWUZhSzM4cjBYTFcxdktzYVlRMmFKc3Q3c0paQTlwSXh6S2FDWS1PXzEtUEtoNExleFBlTlJZMkRCbWw3ZEVn?oc=5", sourceName: "Herzindagi" }
];

export const MARKET_DATA: MarketData = {
  date: NEWS_DATE,
  indices: [
    { name: "תל אביב 125", value: "4,413.10", change: "+0.00%", direction: "stable" },
    { name: "S&P 500", value: "7,230.12", change: "+0.00%", direction: "stable" },
    { name: "נאסדק", value: "25,114", change: "+0.00%", direction: "stable" },
    { name: "דאו גונס", value: "49,499", change: "+0.00%", direction: "stable" }
  ],
  currencies: [
    { name: "דולר/שקל", value: "2.96", change: "+0.00%", direction: "stable" },
    { name: "אירו/שקל", value: "3.46", change: "+0.00%", direction: "stable" },
    { name: "אירו/דולר", value: "1.17", change: "+0.00%", direction: "stable" }
  ],
  commodities: [
    { name: "נפט גולמי", value: "105.25", change: "+0.00%", direction: "stable" },
    { name: "זהב", value: "4,579.30", change: "+0.00%", direction: "stable" },
    { name: "ביטקוין", value: "78,952", change: "+0.00%", direction: "stable" },
    { name: "את'ריום", value: "2,336.82", change: "+0.00%", direction: "stable" },
    { name: "סולנה", value: "83.89", change: "+0.00%", direction: "stable" }
  ],
  israelHeadlines: ["הבורסה בשיאים; נייס מזנקת בכ-19%, השקל נחלש", "עקב הדיווח האיראני על תקיפת ספינה אמריקאית: ירידות בחוזים הע"],
  wallStreetHeadlines: ["Tower Semiconductor maps out four investor conferences in Ma", "Tower Semiconductor (TSEM) plans investor conference meeting"],
  watchTomorrow: "",
};
