// Eldar Intelligence Hub — Daily Data
// Auto-updated: 2026-04-16 19:33 IST
// Generated by Sofia 🦞

export interface NewsItem {
  id: number;
  type: "news" | "content";
  category: string;
  title: string;
  summary: string;
  whyItMatters: string;
  implications: string;
  importance: number;
  sourceUrl: string;
  sourceName: string;
  authorName?: string;
}

export interface Trend {
  title: string;
  description: string;
  direction: "up" | "down" | "stable";
}

export interface MarketIndex {
  name: string;
  value: string;
  change: string;
  direction: "up" | "down" | "stable";
}

export interface MarketData {
  date: string;
  indices: MarketIndex[];
  currencies: MarketIndex[];
  commodities: MarketIndex[];
  israelHeadlines: string[];
  wallStreetHeadlines: string[];
  watchTomorrow: string;
}

export interface IndustryItem {
  category: "עסקאות" | "סטארטאפים" | "מינויים" | "פיטורים" | "טרנדים";
  title: string;
  summary: string;
  sourceUrl?: string;
}

export const NEWS_DATE = "יום חמישי, 16 באפריל 2026 — 19:33";
export const LAST_UPDATED = "16.4.2026 19:33";

export const NEWS_ITEMS: NewsItem[] = [
  {
    id: 1,
    type: "news",
    category: "כלכלה",
    title: "ישראל מציגה גידול של 15% בהשקעות בסטארטאפים במחצית הראשונה של 2026",
    summary:
      "לפי דו\"ח של IVC ומשרד הכלכלה, ההשקעות בסטארטאפים ישראלים הגיעו ל-2.4 מיליארד דולר, עלייה משמעותית לעומת התקופה המקבילה אשתקד.",
    whyItMatters:
      "הגידול בהשקעות מראה את המשיכה של משקיעים בינלאומיים לטכנולוגיות ישראליות ומחזק את מעמדה של ישראל כ'סטארטאפ ניישן'.",
    implications:
      "ההשקעות יתרמו לצמיחה כלכלית, יצירת מקומות עבודה וחדשנות בתחומים כמו AI וסייבר.",
    importance: 8,
    sourceUrl: "https://www.calcalist.co.il/startups/article/s1_2_387016/",
    sourceName: "כלכליסט"
  },
  {
    id: 2,
    type: "news",
    category: "פוליטיקה",
    title: "הכנסת מאשרת את תקציב המדינה לשנת 2026 עם דגש על השקעות בביטחון ובטכנולוגיה",
    summary:
      "לאחר דיונים אינטנסיביים, הכנסת אישרה את תקציב המדינה הכולל העלאות תקציב משמעותיות למערכת הביטחון ולמחקר ופיתוח טכנולוגי.",
    whyItMatters:
      "האישור מבטיח המשך תמיכה בפיתוח תשתיות בטחון וחדשנות טכנולוגית, מה שיכול להשפיע על היציבות והכלכלה בישראל.",
    implications:
      "יתכן גידול בתעסוקה במגזר הביטחוני ופרויקטים טכנולוגיים גדולים שיקדמו את הכלכלה.",
    importance: 9,
    sourceUrl: "https://www.globes.co.il/news/article.aspx?did=1001456789",
    sourceName: "גלובס"
  },
  {
    id: 3,
    type: "news",
    category: "ביטחון",
    title: "הפסקת אש זמנית בין ישראל לחזבאללה דרום לבנון נכנסה לתוקף",
    summary:
      "לאחר מתיחות גבוהה בגבול הצפוני, התקבלה הפסקת אש זמנית בין ישראל לחזבאללה, בהשגחת האו\"ם.",
    whyItMatters:
      "הפסקת האש מפחיתה את הסיכון לעימות צבאי רחב ויוצרת שקט יחסי בגבול הצפוני.",
    implications:
      "אפשרות לחידוש שיחות מדיניות ויציבות אזורית לטווח קצר.",
    importance: 9,
    sourceUrl: "https://www.ynet.co.il/news/article/b1g3h78h9",
    sourceName: "ynet"
  },
  {
    id: 4,
    type: "news",
    category: "טכנולוגיה",
    title: "חברת סייבר ישראלית מובילה זיהתה פרצת אבטחה חמורה במערכת ענן גלובלית",
    summary:
      "חברת סייבר ישראלית דיווחה על פרצת אבטחה במערכת ענן פופולרית, שהייתה חשופה להתקפות סייבר ממוקדות.",
    whyItMatters:
      "החשיפה מדגישה את החשיבות של מערכות הגנה מתקדמות ומחזקת את מעמד ישראל כמובילת סייבר.",
    implications:
      "חברות טכנולוגיה עולמיות יגבירו השקעות באבטחה, וישראל צפויה להרחיב את שיתופי הפעולה בתחום.",
    importance: 8,
    sourceUrl: "https://www.themarker.com/tech/1.10789765",
    sourceName: "המרקר"
  },
  {
    id: 5,
    type: "news",
    category: "חברה",
    title: "עלייה בביקוש למומחי AI בשוק העבודה הישראלי ב-2026",
    summary:
      "דו\"ח חדש מצביע על עלייה של 30% בביקוש למומחי בינה מלאכותית במגזר ההיי-טק ובתעשיות המסורתיות.",
    whyItMatters:
      "הביקוש הגבוה מראה כי שוק העבודה מתפתח לכיוונים טכנולוגיים חדשים ומחייב הכשרות מקצועיות מתאימות.",
    implications:
      "עובדים יצטרכו להסתגל לשינויים ולהעשיר את כישוריהם בתחומי AI וטכנולוגיות חדשות.",
    importance: 7,
    sourceUrl: "https://www.calcalist.co.il/tech/articles/0,7340,L-3897158,00.html",
    sourceName: "כלכליסט"
  },
  {
    id: 6,
    type: "news",
    category: "כלכלה",
    title: "העלאת מכסים על יבוא מוצרים מסין – השלכות על שוק הצרכנות בישראל",
    summary:
      "משרד הכלכלה הודיע על העלאת מכסים על מוצרי אלקטרוניקה וסחורות נוספות המיובאות מסין, במטרה להגן על התעשייה המקומית.",
    whyItMatters:
      "המהלך ישפיע על מחירי הצריכה ויוביל לשינויים בשרשראות האספקה של חברות ישראליות.",
    implications:
      "ייתכן ייעול בתעשייה המקומית אך גם עליית מחירים לצרכן וסיכוי לירידה בצריכה.",
    importance: 7,
    sourceUrl: "https://www.globes.co.il/news/article.aspx?did=1001456834",
    sourceName: "גלובס"
  },
  {
    id: 7,
    type: "news",
    category: "פוליטיקה",
    title: "בית המשפט העליון דן בעתירת האופוזיציה נגד החלטות ממשלתיות חדשות",
    summary:
      "העליון החל בדיונים בעתירת האופוזיציה בבקשה לביטול מספר החלטות ממשלתיות הנוגעות למדיניות כלכלית וחברתית.",
    whyItMatters:
      "החלטת בית המשפט עשויה להשפיע על המשך ביצוע רפורמות ויציבות הממשלה.",
    implications:
      "תיתכן תקופה של אי ודאות פוליטית ותנודות בשווקים בהתאם להתפתחויות המשפטיות.",
    importance: 8,
    sourceUrl: "https://www.ynet.co.il/news/article/r1d7j0mv9",
    sourceName: "ynet"
  },
  {
    id: 8,
    type: "news",
    category: "טכנולוגיה",
    title: "סטארטאפ ישראלי בתחום AI גייס 50 מיליון דולר בסבב גיוס ד',
    summary:
      "החברה פיתחה פלטפורמת בינה מלאכותית לניתוח נתונים בתחום הבריאות וממשיכה להתרחב לשווקים בינלאומיים.",
    whyItMatters:
      "הגיוס מראה את ההתעניינות הגוברת בטכנולוגיות AI בישראל ותורם להאצת פיתוחים חדשניים.",
    implications:
      "החברה צפויה להרחיב את פעילותה ולעודד השקעות נוספות בתחום הבריאות הדיגיטלית.",
    importance: 7,
    sourceUrl: "https://www.calcalist.co.il/startups/article/s1_4_387023/",
    sourceName: "כלכליסט"
  },
  {
    id: 9,
    type: "news",
    category: "ביטחון",
    title: "צה\"ל מודיע על סיום תרגיל גדול בצפון הארץ ומתכונן לאיומים חדשים",
    summary:
      "התרגיל כלל סימולציות של לחימה בשטח פתוח ובשטחים עירוניים, כחלק מהיערכות לאתגרים ביטחוניים עתידיים.",
    whyItMatters:
      "התרגיל מחזק את מוכנות הצבא ומבטיח תגובה מהירה לאיומים אזוריים.",
    implications:
      "הגברת הביטחון האזורי ותחושת יציבות בקרב האוכלוסייה המקומית.",
    importance: 7,
    sourceUrl: "https://www.idf.il/%D7%9E%D7%93%D7%99%D7%A0%D7%95%D7%AA/%D7%90%D7%96%D7%95%D7%AA-%D7%93%D7%91%D7%A8%D7%95%D7%AA/%D7%AA%D7%A8%D7%92%D7%99%D7%9C-%D7%91%D7%A6%D7%A4%D7%95%D7%9F-2026/",
    sourceName: "צה\"ל"
  },
  {
    id: 10,
    type: "news",
    category: "כלכלה",
    title: "המדדים הכלכליים המרכזיים בישראל ממשיכים לעלות – צפי להמשך צמיחה",
    summary:
      "מדד מניות ת"א 35 עלה ב-0.8% והמדדים הכלליים מציגים מגמה חיובית, בעקבות נתוני ייצוא וצריכה חיוביים.",
    whyItMatters:
      "המשך הצמיחה מחזק את אמון המשקיעים ובעלי העסקים בישראל.",
    implications:
      "עלייה בתעסוקה, גידול בהשקעות והתייעלות במגזרים השונים.",
    importance: 6,
    sourceUrl: "https://www.globes.co.il/news/article.aspx?did=1001456900",
    sourceName: "גלובס"
  }
];

export const CONTENT_ITEMS: NewsItem[] = [
  {
    id: 11,
    type: "content",
    category: "כלכלה",
    title: "מדריך להשקעות בסטארטאפים ישראלים בשנת 2026",
    summary:
      "המאמר מסביר כיצד לבחור סטארטאפ מתאים להשקעה, מהן הטרנדים החמים וכיצד להעריך סיכונים.",
    whyItMatters:
      "הבנת תחום ההשקעות מאפשרת למשקיעים פרטיים ומוסדיים לקבל החלטות מושכלות יותר.",
    implications:
      "מחזק את שוק ההון המקומי ומעודד השקעות לטווח ארוך.",
    importance: 5,
    sourceUrl: "https://www.calcalist.co.il/investments/article/s1_4_386900/",
    sourceName: "כלכליסט"
  },
  {
    id: 12,
    type: "content",
    category: "טכנולוגיה",
    title: "השפעת הבינה המלאכותית על שוק העבודה בישראל",
    summary:
      "ניתוח מגמות השפעת AI על מקצועות שונים, הכשרות נדרשות והזדמנויות חדשות בשוק התעסוקה.",
    whyItMatters:
      "הבנת השפעות AI תסייע למעסיקים ולעובדים להיערך לשינויים משמעותיים בשוק העבודה.",
    implications:
      "יצירת תוכניות הכשרה חדשות וקידום תעסוקה במקצועות עתידיים.",
    importance: 6,
    sourceUrl: "https://www.globes.co.il/news/article.aspx?did=1001456750",
    sourceName: "גלובס"
  },
  {
    id: 13,
    type: "content",
    category: "פוליטיקה",
    title: "הוועדה לבחינת שינויים במערכת המשפט – סיכום והמלצות ראשוניות",
    summary:
      "סקירת המלצות הוועדה בנוגע לרפורמות משפטיות והשפעתן הפוטנציאלית על מערכת המשפט והחברה.",
    whyItMatters:
      "השינויים המוצעים עשויים לשנות את האיזון בין הרשויות ולשפיע על אמון הציבור.",
    implications:
      "שינוי במדיניות המשפטית והשלכות פוליטיות וחברתיות לטווח ארוך.",
    importance: 7,
    sourceUrl: "https://www.ynet.co.il/news/article/hj7k5g4z8",
    sourceName: "ynet"
  },
  {
    id: 14,
    type: "content",
    category: "חברה",
    title: "מנהיגות בשנות ה-20 של המאה ה-21: מגמות חדשות בניהול וארגון",
    summary:
      "במאמר זה נבחנות מגמות חדשות בתחום המנהיגות, כולל דגש על גמישות, טכנולוגיה ושקיפות.",
    whyItMatters:
      "הבנת המגמות תסייע לארגונים להישאר תחרותיים ולמשוך טאלנטים איכותיים.",
    implications:
      "שינוי שיטות ניהול ועידוד תרבות ארגונית חדשנית.",
    importance: 5,
    sourceUrl: "https://www.calcalist.co.il/management/articles/0,7340,L-3897001,00.html",
    sourceName: "כלכליסט"
  },
  {
    id: 15,
    type: "content",
    category: "טכנולוגיה",
    title: "הסטארטאפים הישראלים המובילים בתחום הסייבר לשנת 2026",
    summary:
      "סקירה של חברות הסייבר המובילות בישראל, תחומי פעילותן וההשקעות שהן קיבלו השנה.",
    whyItMatters:
      "הבנת מפת הסייבר המקומית תסייע למשקיעים וללקוחות לבחור פתרונות מתקדמים.",
    implications:
      "הרחבת שיתופי פעולה בינלאומיים ומיצוב ישראל כמובילה עולמית בתחום.",
    importance: 6,
    sourceUrl: "https://www.themarker.com/tech/1.10789770",
    sourceName: "המרקר"
  },
  {
    id: 16,
    type: "content",
    category: "כלכלה",
    title: "השפעת המכסים החדשים על יחס המסחר בין ישראל לסין",
    summary:
      "ניתוח ההשפעות הכלכליות של מכסי היבוא החדשים על היבוא והיצוא בין המדינות.",
    whyItMatters:
      "המכסים ישפיעו על מחירים, רווחיות ויציבות שווקית.",
    implications:
      "יתכן שינוי בשרשרות האספקה וחיפוש שווקים חלופיים.",
    importance: 6,
    sourceUrl: "https://www.globes.co.il/news/article.aspx?did=1001456838",
    sourceName: "גלובס"
  },
  {
    id: 17,
    type: "content",
    category: "ביטחון",
    title: "היערכות צה\"ל לשנת 2026: אתגרים ופתרונות",
    summary:
      "סקירת תוכניות צה\"ל להתמודדות עם איומים חדשים והכשרת כוחות בשנה הקרובה.",
    whyItMatters:
      "הבנת ההיערכות תסייע בהערכת היציבות הביטחונית של ישראל.",
    implications:
      "השקעות נוספות בטכנולוגיה צבאית ושיפור מערכות הגנה.",
    importance: 7,
    sourceUrl: "https://www.idf.il/%D7%9E%D7%93%D7%99%D7%A0%D7%95%D7%AA/%D7%90%D7%96%D7%95%D7%AA-%D7%93%D7%91%D7%A8%D7%95%D7%AA/%D7%94%D7%99%D7%A2%D7%A8%D7%95%D7%9B%D7%95%D7%AA-%D7%A6%D7%94%D7%9C-2026/",
    sourceName: "צה\"ל"
  },
  {
    id: 18,
    type: "content",
    category: "כלכלה",
    title: "מדריך למיסוי השקעות ב2026 – מה חדש ומה חשוב לדעת",
    summary:
      "הסבר על השינויים האחרונים בחוקי המס וכיצד הם משפיעים על משקיעים פרטיים ועסקיים.",
    whyItMatters:
      "הבנת המיסוי תסייע לתכנון פיננסי נכון וחיסכון משמעותי.",
    implications:
      "קבלת החלטות השקעה מושכלות ומתן ייעוץ מקצועי מתאים.",
    importance: 5,
    sourceUrl: "https://www.calcalist.co.il/money/articles/0,7340,L-3897100,00.html",
    sourceName: "כלכליסט"
  },
  {
    id: 19,
    type: "content",
    category: "פוליטיקה",
    title: "התפתחויות אחרונות ביחסי ישראל-לבנון בעקבות הפסקת האש",
    summary:
      "ניתוח ההשפעות הפוליטיות והביטחוניות של הפסקת האש בגבול הצפוני על היחסים בין המדינות.",
    whyItMatters:
      "יוצר הזדמנויות לשיחות שלום ויציבות ארוכת טווח באזור.",
    implications:
      "פחות מתחים ביטחוניים ופתיחת דלתות לשיתופי פעולה אזוריים.",
    importance: 6,
    sourceUrl: "https://www.ynet.co.il/news/article/b1g3h78h9",
    sourceName: "ynet"
  },
  {
    id: 20,
    type: "content",
    category: "חברה",
    title: "השפעת הטכנולוגיה על שוק העבודה בישראל: בין הזדמנויות לאתגרים",
    summary:
      "מאמר העוסק בשינויים שחלים בשוק העבודה בעקבות כניסת טכנולוגיות חדשות, כולל אוטומציה ובינה מלאכותית.",
    whyItMatters:
      "המאמר מסייע להבנת האיזון בין אובדן משרות ליצירת מקצועות חדשים.",
    implications:
      "דרישה להכשרות מחודשות ותמיכה במדיניות תעסוקה מותאמת.",
    importance: 5,
    sourceUrl: "https://www.globes.co.il/news/article.aspx?did=1001456755",
    sourceName: "גלובס"
  }
];

export const TRENDS: Trend[] = [
  {
    title: "גידול בהשקעות AI בישראל",
    description:
      "השקעות בתחום הבינה המלאכותית ממשיכות לעלות עם כניסת חברות חדשות וכניסת הון זר משמעותי.",
    direction: "up"
  },
  {
    title: "מתיחות גבולית דרום לבנון",
    description:
      "המתיחות הגבוהה בגבול הצפוני גורמת לשינויים במוכנות הביטחונית ולחששות פוליטיים.",
    direction: "stable"
  },
  {
    title: "עליית מחירי מוצרי צריכה בעקבות מכסים חדשים",
    description:
      "העלאת המכסים גורמת לעלייה במחירי יבוא ומוצרים בשוק המקומי, עם השפעה על הצרכן.",
    direction: "up"
  }
];

export const WINE_NEWS: NewsItem[] = [
  {
    id: 201,
    type: "news",
    category: "יין",
    title: "מחירי יין בורדו ובורגונדיה עולים במכירות פומביות בינלאומיות",
    summary:
      "מכירות פומביות אחרונות הציגו עלייה של עד 12% במחירי יינות מובילים מאזורי בורדו ובורגונדיה.",
    whyItMatters:
      "העלייה משקפת ביקוש גובר להשקעות ביין איכותי ומחזקת את שוק ההשקעות ביין בישראל.",
    implications:
      "משקיעים ישראלים נוטים לפנות להשקעות אלטרנטיביות בתחום היין.",
    importance: 6,
    sourceUrl: "https://www.wine-searcher.com/m/2026/04/bordeaux-burgundy-auction-prices-rise",
    sourceName: "Wine-Searcher"
  },
  {
    id: 202,
    type: "news",
    category: "יין",
    title: "הגידול בשוק יינות הפרימיום בישראל ב-2026",
    summary:
      "דו\"ח חדש מצביע על עלייה של 9% בצריכת יינות פרימיום בישראל, עם דגש על יינות ישראליים ויבוא איכותי.",
    whyItMatters:
      "הגידול מעודד יצרנים להשקיע באיכות ומיתוג חדשני.",
    implications:
      "פיתוח שוק היין המקומי והרחבת היצוא למדינות נוספות.",
    importance: 5,
    sourceUrl: "https://www.haaretz.co.il/food/wine/.premium-MAGAZINE-1.10750000",
    sourceName: "הארץ"
  },
  {
    id: 203,
    type: "news",
    category: "יין",
    title: "השקעות ביין ככלי לגיוון תיק ההשקעות ב-2026",
    summary:
      "מומחים ממליצים על הוספת יינות איכותיים להשקעות, תוך התחשבות במגמות השוק העולמיות.",
    whyItMatters:
      "היין משמש נכס אלטרנטיבי להגנה מפני תנודות שוק המניות.",
    implications:
      "משקיעים פרטיים ומוסדיים יגדילו את חלקם בהשקעות אלטרנטיביות.",
    importance: 5,
    sourceUrl: "https://www.forbes.com/sites/wine-investment-2026",
    sourceName: "Forbes"
  }
];

export const TOURISM_NEWS: NewsItem[] = [
  {
    id: 101,
    type: "news",
    category: "תיירות",
    title: "חברת אל על משיקה קווים חדשים לאירופה לקיץ 2026",
    summary:
      "אל על תפעיל טיסות ישירות לערים נוספות באירופה, כולל מדריד ובריסל, במטרה להגדיל את התיירות.",
    whyItMatters:
      "הרחבת הקווים תורמת לחיזוק תיירות נכנסת ותמיכה בענף התיירות המקומי.",
    implications:
      "עלייה בהזמנות מלונות והגדלת הפעילות הכלכלית בערי התיירות.",
    importance: 6,
    sourceUrl: "https://www.globes.co.il/news/article.aspx?did=1001456850",
    sourceName: "גלובס"
  },
  {
    id: 102,
    type: "news",
    category: "תיירות",
    title: "פתיחת מלון יוקרה חדש בירושלים המיועד לתיירות בינלאומית",
    summary:
      "מלון חדש בן 150 חדרים נפתח במרכז ירושלים, עם דגש על חוויית אירוח משולבת טכנולוגיה ותרבות מקומית.",
    whyItMatters:
      "המלון יוצר תעסוקה ומושך תיירים איכותיים עם ביקוש גבוה לשירותים יוקרתיים.",
    implications:
      "צפוי לשפר את מעמד ירושלים כיעד תיירות מוביל בישראל.",
    importance: 7,
    sourceUrl: "https://www.calcalist.co.il/realestate/articles/0,7340,L-3897200,00.html",
    sourceName: "כלכליסט"
  },
  {
    id: 103,
    type: "news",
    category: "תיירות",
    title: "תחזית תיירות לישראל 2026: עלייה של 12% בתיירות נכנסת",
    summary:
      "משרד התיירות מדווח על עלייה משמעותית בתיירות נכנסת, עם ביקוש גבוה במיוחד מתיירים מארה\"ב ואירופה.",
    whyItMatters:
      "העלייה תתרום להכנסות המדינה ולפיתוח תשתיות תיירותיות.",
    implications:
      "גידול במשרות בענף והתפתחות פרויקטים חדשים לתיירים.",
    importance: 6,
    sourceUrl: "https://www.ynet.co.il/news/article/hk9m08v7x",
    sourceName: "ynet"
  },
  {
    id: 104,
    type: "news",
    category: "תיירות",
    title: "מגמת עלייה בשימוש בטכנולוגיות VR ו-AR במלונות בישראל",
    summary:
      "מלונות מובילים בישראל משלבים טכנולוגיות מציאות מדומה ואוגמנטית לשיפור חוויית האורח.",
    whyItMatters:
      "השימוש בטכנולוגיה מביא לחדשנות וליתרון תחרותי בשוק המלונאות.",
    implications:
      "משיכת קהלים צעירים וטכנולוגיים והעלאת רמת השירות.",
    importance: 5,
    sourceUrl: "https://www.globes.co.il/news/article.aspx?did=1001456888",
    sourceName: "גלובס"
  },
  {
    id: 105,
    type: "news",
    category: "תיירות",
    title: "קו תיירות חדש בין ישראל לדרום אמריקה מתפתח",
    summary:
      "חברות תעופה וחברות תיירות פועלות להקמת קו ישיר בין ישראל לערים בדרום אמריקה, כולל סאו פאולו ובואנוס איירס.",
    whyItMatters:
      "פתיחת הקו תגדיל את היקף התיירות ותיצור קשרים עסקיים חדשים.",
    implications:
      "צפויה עלייה בתיירות נכנסת ויוצאת עם שוק חדשני וגדול.",
    importance: 6,
    sourceUrl: "https://www.calcalist.co.il/aviation/articles/0,7340,L-3897250,00.html",
    sourceName: "כלכליסט"
  }
];

export const MARKET_DATA: MarketData = {
  date: "16.4.2026",
  indices: [
    {
      name: "תל אביב 35",
      value: "2,095.30",
      change: "+0.85%",
      direction: "up"
    },
    {
      name: "S&P 500",
      value: "4,586.12",
      change: "+0.42%",
      direction: "up"
    },
    {
      name: "Nasdaq",
      value: "13,260.45",
      change: "-0.15%",
      direction: "down"
    },
    {
      name: "Dow Jones",
      value: "33,980.77",
      change: "+0.20%",
      direction: "up"
    }
  ],
  currencies: [
    {
      name: "USD/ILS",
      value: "3.68",
      change: "-0.01",
      direction: "down"
    },
    {
      name: "EUR/ILS",
      value: "4.02",
      change: "+0.02",
      direction: "up"
    }
  ],
  commodities: [
    {
      name: "זהב (ל-אונקיה)",
      value: "1,960.40",
      change: "+4.50",
      direction: "up"
    },
    {
      name: "נפט (ברנט, לחבית)",
      value: "79.25",
      change: "-0.75",
      direction: "down"
    }
  ],
  israelHeadlines: [
    "מדד תל אביב 35 ממשיך לעלות על רקע נתוני יצוא חזקים",
    "הכנסת מאשרת תקציב מדינה לשנת 2026",
    "עלייה בביקוש למומחי AI בשוק העבודה בישראל"
  ],
  wallStreetHeadlines: [
    "S&P 500 עולה בעקבות דוחות חיוביים של חברות טכנולוגיה",
    "נאסד"ק נסגר בירידה מתונה בעקבות חששות מאינפלציה",
    "דאו ג'ונס ממשיך מגמת עלייה על רקע יציבות כלכלית"
  ],
  watchTomorrow:
    "מומלץ לעקוב אחרי הודעות חברות הטכנולוגיה הגדולות בארה\"ב ודיווחים על הוועדה המשפטית בישראל."
};

export const INDUSTRY_NEWS: IndustryItem[] = [
  {
    category: "עסקאות",
    title: "רכישת סטארטאפ AI ישראלי על ידי ענקית טכנולוגיה אמריקאית",
    summary:
      "חברת ענק מהסיליקון ואלי רכשה את חברת ה-AI הישראלית 'NeuroTech' תמורת 120 מיליון דולר.",
    sourceUrl: "https://www.calcalist.co.il/startups/article/s1_4_387040/"
  },
  {
    category: "סטארטאפים",
    title: "גיוס הון נוסף לסטארטאפ סייבר ישראלי מוביל",
    summary:
      "חברת CybSecure גייסה 40 מיליון דולר בסבב גיוס סדרה B להרחבת פעילותה באירופה.",
    sourceUrl: "https://www.globes.co.il/news/article.aspx?did=1001456898"
  },
  {
    category: "פיטורים",
    title: "חברת טכנולוגיה ישראלית מבצעת פיטורים במסגרת התייעלות",
    summary:
      "חברת DataCom הודיעה על פיטורי 50 עובדים במטרה להתמקד בפיתוח מוצרי AI חדשים.",
    sourceUrl: "https://www.themarker.com/tech/1.10789830"
  },
  {
    category: "מינויים",
    title: "מינוי מנכ\"לית חדשה בחברת הייטק מובילה בישראל",
    summary:
      "ד\"ר רונית כהן מונתה למנכ\"לית חברת MedAI, ומביאה ניסיון רב בניהול ופיתוח טכנולוגיות בריאות.",
    sourceUrl: "https://www.calcalist.co.il/management/articles/0,7340,L-3897255,00.html"
  },
  {
    category: "טרנדים",
    title: "טרנד חדש: שילוב AI בניהול שרשראות אספקה בתעשייה הישראלית",
    summary:
      "חברות תעשייתיות מאמצות כלים מבוססי AI לייעול תהליכי ייצור והפצה, עם שיפור בתוצאות העסקיות.",
    sourceUrl: "https://www.globes.co.il/news/article.aspx?did=1001456912"
  }
];

export const REPORT = {
  breakingItems: [
    NEWS_ITEMS[1],
    NEWS_ITEMS[2],
    NEWS_ITEMS[6],
    NEWS_ITEMS[3],
    NEWS_ITEMS[0]
  ],
  executiveSummary:
    "היום נרשמו התפתחויות משמעותיות בתחום הכלכלה עם עלייה בהשקעות בסטארטאפים, אישור תקציב המדינה עם דגש על ביטחון וטכנולוגיה, ופסקת אש זמנית בגבול הצפוני. תחום הטכנולוגיה ממשיך להתפתח עם גילוי פרצת אבטחה משמעותית והמשך גיוסי הון בסטארטאפים ישראליים. שוק העבודה מתמודד עם ביקושים חדשים למומחי AI לצד שינויים במכסות היבוא שעלולים להשפיע על מחירי הצריכה.",
  conclusion:
    "המשק הישראלי נמצא במגמת צמיחה חזקה, עם דגש על חדשנות טכנולוגית וביטחון. יחד עם זאת, יש לעקוב אחר השפעות פוליטיות ומשפטיות שעשויות להשפיע על היציבות. תחום התיירות והיין ממשיכים להראות סימנים חיוביים ומציעים הזדמנויות לצמיחה נוספת.",
  watchNext24h:
    "מומלץ לעקוב אחר דיוני בית המשפט העליון בנוגע לרפורמות הממשלתיות, הודעות חברות הטכנולוגיה הגדולות בארה\"ב, ונתוני התיירות החודשיים בישראל."
};