// Eldar Intelligence Hub — Daily Data
// Auto-updated: 20:36 01.05.2026 IST
// Generated by Sofia v11 — Real Data Only, GPT for Insights Only
export interface NewsItem {
  id: number;
  type: "news" | "content";
  category: string;
  title: string;
  summary: string;
  whyItMatters: string;
  implications: string;
  importance: number;
  sourceUrl: string;
  sourceName: string;
  authorName?: string;
}

export interface Trend {
  title: string;
  description: string;
  direction: "up" | "down" | "stable";
}

export interface MarketIndex {
  name: string;
  value: string;
  change: string;
  direction: "up" | "down" | "stable";
}

export interface MarketData {
  date: string;
  indices: MarketIndex[];
  currencies: MarketIndex[];
  commodities: MarketIndex[];
  israelHeadlines: string[];
  wallStreetHeadlines: string[];
  watchTomorrow: string;
}

export const NEWS_DATE = "01.05.2026";

export const LAST_UPDATED = "20:36 01.05.2026";

export const REPORT = {
  date: NEWS_DATE,
  breakingItems: ["📈 נאסדק עולה ביותר מ-1%, אורקל מזנקת ביותר מ-6%", "🏛️ חשד לרצח ברהט: גבר כבן 30 נהרג, המשטרה פתחה בחקירה - וואלה ח", "⚔️ IDF: Iron Beam laser saw limited use in Iran war due to lack", "👥 שפל חדש: על סף 100 נרצחים - תוך 4 חודשים", "🤖 גיקטיים | למרות הקיצוצים בחטיבת ה-Metaverse, מטא ממשיכה לשרו"],
  executiveSummary: "היום אנו רואים חיזוק בשוק ההייטק והנדל״ן בישראל לצד אתגרים ביטחוניים וחברתיים משמעותיים. שיתופי פעולה ביטחוניים עם מדינות המפרץ מתעצמים, בעוד שהשוק הטכנולוגי ממשיך להתפתח עם דגש על בינה מלאכותית וניהול דאטה. במקביל, עליית מקרי האלימות מחייבת תשומת לב מיוחדת לשמירת היציבות הפנימית.",
  conclusion: "המצב הנוכחי מחייב איזון בין פיתוח כלכלי לבין התמודדות עם אתגרים ביטחוניים וחברתיים.",
  watchNext24h: "יש לעקוב אחרי התפתחויות ביטחוניות בגבולות ולראות כיצד ישפיעו על שוק ההון והתעשייה המקומית.",
};

export const NEWS_ITEMS: NewsItem[] = [
  { id: 1, type: "news", category: "כלכלה", title: "נאסדק עולה ביותר מ-1%, אורקל מזנקת ביותר מ-6%", summary: "מניית אפל מזנקת בכ-5% לאחר פרסום דוחות חזקים, בעוד מניית רובלוקס צונחת - הביטקוין מתחזק בכ-2.6% - באירופה לא היה היום מסחר בגלל האחד המאי", whyItMatters: "עלייה בנאסדק ואורקל משקפת חיזוק בשוק הטכנולוגיה העולמי, המשפיע על חברות ישראליות בתחום ההייטק וההשקעות.", implications: "צפוי גידול בהשקעות בחברות טכנולוגיה ישראליות ובשיתופי פעולה עם חברות אמריקאיות מובילות.", importance: 7, sourceUrl: "https://www.globes.co.il/news/article.aspx?did=1001541680#utm_source=RSS", sourceName: "גלובס" },
  { id: 2, type: "news", category: "כלכלה", title: "מניות הנדל״ן הזניקו את ת״א. זה המדד שננעל בשיא", summary: "יום המסחר ננעל עם שיא חדש של תל אביב 125; מדד תל אביב 90 זינק בכ-1.9% - מניות הבנייה הובילו את העליות, כשברקע האפשרות להורדת ריבית גבוהה יותר מהצפי - החוזים העתידיים על וול סטריט רושמים עליות קלות", whyItMatters: "עלייה במניות הנדל״ן בתל אביב מצביעה על חיזוק מגזר הנדל״ן המקומי, המשפיע על משקיעים ויזמים בישראל.", implications: "ייתכן המשך עליות במחירי הנדל״ן והזדמנויות חדשות להשקעות בתחום הנדל״ן המניב.", importance: 7, sourceUrl: "https://www.globes.co.il/news/article.aspx?did=1001541652#utm_source=RSS", sourceName: "גלובס" },
  { id: 3, type: "news", category: "פוליטיקה", title: "חשד לרצח ברהט: גבר כבן 30 נהרג, המשטרה פתחה בחקירה - וואלה חדשות", summary: "חשד לרצח ברהט: גבר כבן 30 נהרג, המשטרה פתחה בחקירה וואלה חדשות", whyItMatters: "חשד לרצח בברהט מדגיש אתגרים ביטחוניים וחברתיים במגזרים מסוימים בישראל, המשפיעים על יציבות האזור.", implications: "חשוב לעקוב אחרי תגובות המשטרה והמדינה לשמירה על ביטחון האזרחים ויציבות חברתית.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMiTkFVX3lxTFA0VjlObjVxaWp6UUZ4X3RrMFZwcTZPRWxCQjZRVXNPS21zX2pKNmJtZU5fQXZUTUxqaGdrMlFjWUFRQ1BzQnJYazlCRUN4UQ?oc=5", sourceName: "וואלה חדשות" },
  { id: 4, type: "news", category: "פוליטיקה", title: "אם כולנו משוועים למנהיג חדש, למה בנט? - ynet.co.il", summary: "אם כולנו משוועים למנהיג חדש, למה בנט? ynet.co.il", whyItMatters: "דיון על מנהיגות פוליטית בישראל משקף חוסר ודאות פוליטית שעשויה להשפיע על יציבות השלטון והמדיניות הכלכלית.", implications: "ייתכן שינוי במנהיגות או במדיניות, מה שיכול להשפיע על שוק ההון וההשקעות בארץ.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMiWkFVX3lxTE93dWtUWlN4bGZKQ2cyb2tsSS1ZZlN1QlNmN0xKX0JpT0dGUE01OVlnY0doR0MwYTJsRllJcm9LLXhIOGlqZlNZMFFUQk5jcnRhLS1KSWZCZUp5UQ?oc=5", sourceName: "ynet.co.il" },
  { id: 5, type: "news", category: "צבא וביטחון", title: "IDF: Iron Beam laser saw limited use in Iran war due to lack of batteries, 14 needed - The Jerusalem Post", summary: "IDF: Iron Beam laser saw limited use in Iran war due to lack of batteries, 14 needed The Jerusalem Post", whyItMatters: "שימוש מוגבל במערכת לייזר Iron Beam במלחמה באיראן מדגים את האתגרים הטכנולוגיים והלוגיסטיים במערכות הגנה מתקדמות.", implications: "חשוב לשפר את תשתיות הסוללות כדי להרחיב את השימוש במערכות הגנה לייזר בעתיד.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMibkFVX3lxTFBrU2lVZTA2ZXcyVDQyVEJveUlGd0tYT0dNS1o0eE9xUHJXb3JuVW1IWEtGOFk3YlZfcHg3WFZwYWo3VXhBTko2TW1lbzBoR01jYmdsWklxWldQUmFteG85b25HMU13bTFBRVVMMm1B?oc=5", sourceName: "The Jerusalem Post" },
  { id: 6, type: "news", category: "צבא וביטחון", title: "Israel sent laser system to UAE to help intercept Iranian missiles and drones — report - The Times of Israel", summary: "Israel sent laser system to UAE to help intercept Iranian missiles and drones — report The Times of Israel", whyItMatters: "העברת מערכת לייזר לאיחוד האמירויות מחזקת את שיתוף הפעולה הביטחוני באזור ומגבירה את ההגנה מול איומי איראן.", implications: "צפוי חיזוק הקשרים הביטחוניים והטכנולוגיים בין ישראל לאמירויות, עם השפעות על יציבות האזור.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMitgFBVV95cUxPOEh3STZGWDA4VDdESXczWElzcEg2ZlNvOUZHVXBBUldfNmFVcWMtbFRNelB1MnRKRnJNRG5UbkRndHR3NlBBamxnZVYzVE1hWEE3Wk16Ti1yeURTNVlJR1poenppQ2Zxcm42b3kwdVE2MTRpR29kc0JseUxuSy1mc1BmOWZPODFXZ2NfWEpTRUJTbWxZWTNud2JnT05kZmxKVm9YT0o1bVNMT0F6aEpXVGJhUXplUdIBuwFBVV95cUxNOGc2SFBjTENDWWNiNWhYQlNsR3hXYm5fbzZWWGZGSHZTaDVRVGZWTkdzMnFmRnBOX3k1UFVQSVRBZ3RCb2Y0YVRTOVFtMWo4QWNDX1NXYVdDdkxHYUh3ZnFFODV4dkdOVnJ6QW1GUnNjUlRPdkEtSERnNVZzN0tNYkdwSXM2ZHBRdUtVNVFzN1FpV2Q0LXNvWTdDQTJmVjk0LUFLQjV2Uk4xQk91WWNOOWNqOVVBb2Jvdl9N?oc=5", sourceName: "The Times of Israel" },
  { id: 7, type: "news", category: "חברה", title: "שפל חדש: על סף 100 נרצחים - תוך 4 חודשים", summary: "איסמעיל אבו עאבד (27) נורה למוות ברהט. הוא הנרצח ה-97 בחברה הערבית מתחילת השנה - וגם ביחס לשנה המדממת הקודמת המספר הזה חסר תקדים", whyItMatters: "עלייה במספר הנרצחים מצביעה על בעיות ביטחוניות וחברתיות חמורות בישראל, המשפיעות על תחושת הביטחון הציבורית.", implications: "דרוש טיפול מיידי במניעת אלימות ושיפור אמצעי האכיפה והחינוך.", importance: 7, sourceUrl: "https://www.ynet.co.il/news/article/h194gwf0zg", sourceName: "ynet" },
  { id: 8, type: "news", category: "חברה", title: "הרמטכל הורה: לתקוף את שרשרת ייצור ואספקת רחפני הנפץ - גם בעומק לבנון", summary: "פרסום ראשון: ראל זמיר הנחה את פיקוד צפון וחיל האוויר לתקוף לא רק בדרום המדינה מול איום הרחפנים, שמהם נהרגו בשבוע האחרון שני לוחמים ואזרח", whyItMatters: "הוראת הרמטכ״ל לתקוף שרשרת ייצור רחפני נפץ בלבנון מצביעה על התגברות פעולות ביטחוניות נגד איומים חדשים.", implications: "צפוי גידול בפעילות צבאית באזור, המשפיע על יציבות הגבול והסיכונים הביטחוניים.", importance: 7, sourceUrl: "https://www.ynet.co.il/news/article/r1oqoumrbl", sourceName: "ynet" },
  { id: 9, type: "news", category: "טכנולוגיה", title: "גיקטיים | למרות הקיצוצים בחטיבת ה-Metaverse, מטא ממשיכה לשרוף כסף על VR - גיקטיים", summary: "גיקטיים | למרות הקיצוצים בחטיבת ה-Metaverse, מטא ממשיכה לשרוף כסף על VR גיקטיים", whyItMatters: "המשך ההשקעה של מטא ב-VR למרות קיצוצים מצביע על אמונה בטכנולוגיות מציאות מדומה לטווח ארוך.", implications: "חברות ישראליות בתחום ה-VR יכולות להרוויח מהמשך פיתוח וחדשנות בתחום זה.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMib0FVX3lxTE9zV1g1dUI4aDcya2xEc2VIWGh6Ukp2NzhlaG5ObXBod2lGVWhLSmVaRnItbUo5ZnJyaXFJZXc3YlUteldiR05FOFBKOVhPOTVleEhMMGZ0aVFOdW5qSEYxZWktQXFKYXJBanpHc0dJbw?oc=5", sourceName: "גיקטיים" },
  { id: 10, type: "news", category: "טכנולוגיה", title: "גייסו 12 מיליון דולר כדי שסוכני ה-AI יעשו סדר בדאטה שלכם - גיקטיים", summary: "גייסו 12 מיליון דולר כדי שסוכני ה-AI יעשו סדר בדאטה שלכם גיקטיים", whyItMatters: "גיוס הון לסוכני AI לניהול דאטה מראה על צורך גובר בפתרונות בינה מלאכותית לניהול מידע בארגונים.", implications: "חברות ישראליות יכולות להוביל בפיתוח כלים לניהול דאטה מבוססי AI ולהגדיל את התחרותיות שלהן.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMieEFVX3lxTE1TQl8yUVktRW45R1dreWVGOGNmMGpUTzVVTlJobEI1UUFrYllVdFlYdnBRNS0yemExMDVsZzVVWi10OFBYa2tPdTVjcV9pUXlwbmQ4RU1lYXlia3RqdXlZUzR2SDJHNm1oOWtIV19iM3hZSnk1eEZLcw?oc=5", sourceName: "גיקטיים" },
  { id: 11, type: "news", category: "אירועים", title: "Radware lines up 3 investor conferences, with a May 14 webcast - Stock Titan", summary: "Radware lines up 3 investor conferences, with a May 14 webcast Stock Titan", whyItMatters: "כנסי משקיעים של Radware מסמנים הזדמנויות לגיוס הון ולהצגת טכנולוגיות סייבר מתקדמות.", implications: "משקיעים ישראלים צריכים לעקוב אחרי ההזדמנויות להשקעה בחברות סייבר מובילות.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMinwFBVV95cUxNLUcwNmdZWjZlX2VfTEEzUlpUQV85amdsR1o4TXJaYXg3eFlkbHgxM25NMU1IRVVScU9GVXFZNi1iNGEwd0hxWUJzclVNR0FPX3BycmVzamg5eVhvRGduckdBZFVtMnU4SHFGN1B0d1QtUGJBY1Yzem90LTluZXg5RG9meVBwYVJnRjNDUUUxcXI0VktBZVowc2hiNUdqM3M?oc=5", sourceName: "Stock Titan" },
  { id: 12, type: "news", category: "אירועים", title: "Check Point Software Reports 2026 First Quarter Financial Results - PR Newswire", summary: "Check Point Software Reports 2026 First Quarter Financial Results PR Newswire", whyItMatters: "דוחות פיננסיים של Check Point משקפים את מצב שוק אבטחת המידע, תחום מרכזי בתעשיית ההייטק הישראלית.", implications: "תוצאות חיוביות יכולות לעודד השקעות נוספות ולהשפיע על שוק המניות הטכנולוגיות בישראל.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMivgFBVV95cUxNdzVhWE5aWnpKNGl2aVkwR3IxeE9SRE0ya3NMZWNwX2VhQ0JNVmZxTzZOUlFFMXF4ck9tODZPM3pEak9YVHFHa25ZbnJsb1EwOFV2SFJxRWlkVjEybHVGUXJWRzFmNHdWY1FrNzQ3ejc1dFI3STBIMnB1dVVTS0VLQ1U4empPamE5MFM4cEVVX25lZ2tYWTNTY3llRVNsNnktd0k4cHgwbVo4bTRSRGMtcllzZ2ZCQjh0eVRSYVpn?oc=5", sourceName: "PR Newswire" },
  { id: 13, type: "news", category: "בידור", title: "The 28 Best New Shows of 2026 (and 24 More We Can't Wait For) - Men's Health", summary: "The 28 Best New Shows of 2026 (and 24 More We Can't Wait For) Men's Health", whyItMatters: "רשימת תוכניות חדשות משקפת מגמות צריכה בתרבות ובידור, המשפיעות על שוק המדיה והפרסום בישראל.", implications: "חברות ישראליות בתחום המדיה יכולות לנצל הזדמנויות לשיתופי פעולה ולהרחבת התוכן.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMie0FVX3lxTFBrT2o2RUtxbTY4TUlkMS1BUkhQa3pncDY1Qmd1allKeU5nRHoyb1BLbld4bnh3eGl5OGM2TlljdExvZkZQX05QeFdpN0IxWWxpQUtsX2NGazVuM3czX1hiWmc0bWVremh2eDhQd0dPcEFTM3VvWkZNd3JsOA?oc=5", sourceName: "Men's Health" },
  { id: 14, type: "news", category: "בידור", title: "Netflix’s New Releases Coming in May 2026 - The Hollywood Reporter", summary: "Netflix’s New Releases Coming in May 2026 The Hollywood Reporter", whyItMatters: "הכרזות על שחרורי נטפליקס חדשים משפיעות על תחרות בשוק הסטרימינג, עם השפעה על צריכת המדיה בישראל.", implications: "חברות הפקה ישראליות יכולות להגדיל שיתופי פעולה ולהרחיב הפצה בינלאומית.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMinAFBVV95cUxQTWRtTldnODJYYkpOaF9pZE9JZFRkMXEtUENtbEd4M0VvZXVmUFhxWnFhRXE2SDVveTJBbE9GeldONTVTU3VMajhrVm4tY3E1dnZtVnlaOFlEd0JTS2EzRXgtUld1RTVqRW1CUElIRWE0T2NoemEzcFhpRHphaW44N2Z2SVA3QklWeDNjSkpRUXNXQl9XSlZacS1hdzA?oc=5", sourceName: "The Hollywood Reporter" },
  { id: 15, type: "news", category: "פיתוח אישי", title: "גרג ברוקמן: מבפנים 72 השעות שכמעט הרגו את OpenAI", summary: "מרוץ הבינה המלאכותית, עתיד ה-AGI, והסיפור מבפנים של OpenAI. גרג ברוקמן הוא מייסד שותף ונשיא OpenAI, החברה שמאחורי ChatGPT ו-GPT-5. הוא היה המהנדס הראשון ב-Stripe לפני כן.", whyItMatters: "סיפורו של גרג ברוקמן על משבר ב-OpenAI מדגיש את האתגרים בניהול חברות AI גדולות, רלוונטי לתעשיית ההייטק בישראל.", implications: "חברות ישראליות בתחום הבינה המלאכותית צריכות להתכונן לאתגרים דומים ולפתח ניהול סיכונים מתאים.", importance: 7, sourceUrl: "https://fs.blog/knowledge-project-podcast/greg-brockman/", sourceName: "Farnam Street" },
  { id: 16, type: "news", category: "פיתוח אישי", title: "מריו האריק: משחק לניצחון", summary: "מריו האריק הוא מנהל כללי XPO, אחת מחברות הלוגיסטיקה הגדולות בעולם. במשך שנים היה תלמידו של היזם האגדי ברד ג'ייקובס, שבנה שמונה חברות בשווי מיליארדי דולרים.", whyItMatters: "הצלחתו של מריו האריק במשחקים מדגימה את חשיבות האסטרטגיה והחדשנות בתחרות עסקית וטכנולוגית.", implications: "מנהלים ישראלים יכולים ללמוד מהשיטות האסטרטגיות לשיפור ביצועים והובלת שווקים.", importance: 7, sourceUrl: "https://fs.blog/knowledge-project-podcast/mario-harik/", sourceName: "Farnam Street" }
];

export const CONTENT_ITEMS: NewsItem[] = [
  { id: 100, type: "content", category: "טכנולוגיה", title: "גיקטיים | למרות הקיצוצים בחטיבת ה-Metaverse, מטא ממשיכה לשרוף כסף על VR - גיקטיים", summary: "גיקטיים | למרות הקיצוצים בחטיבת ה-Metaverse, מטא ממשיכה לשרוף כסף על VR גיקטיים", whyItMatters: "השפעה על תעשיית ההייטק והחדשנות", implications: "השפעה על תעשיית ההייטק והחדשנות", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMib0FVX3lxTE9zV1g1dUI4aDcya2xEc2VIWGh6Ukp2NzhlaG5ObXBod2lGVWhLSmVaRnItbUo5ZnJyaXFJZXc3YlUteldiR05FOFBKOVhPOTVleEhMMGZ0aVFOdW5qSEYxZWktQXFKYXJBanpHc0dJbw?oc=5", sourceName: "גיקטיים" },
  { id: 101, type: "content", category: "כלכלה", title: "אפריל המדהים בגמל: המסלול שעקף את כולם ואלו שכמעט שברו שיא של 15 שנה", summary: "החוסכים בקופות הגמל נהנו בחודש החולף מתשואה פנומנלית של כ-4.2% במסלול הכללי וכ-8.3% במסלול המנייתי - למרות הביצועים העודפים של השוק האמריקאי מסלולי ה-S&P 500 עם תשואה של 2.5%, בשל התחזקות הש", whyItMatters: "השפעה אפשרית על שוק ההון ועל הכלכלה הישראלית", implications: "השפעה אפשרית על שוק ההון ועל הכלכלה הישראלית", importance: 6, sourceUrl: "https://www.globes.co.il/news/article.aspx?did=1001541678#utm_source=RSS", sourceName: "גלובס" },
  { id: 102, type: "content", category: "צבא וביטחון", title: "מכבי חיפה מושפלת: \"אחת הקבוצות החלשות שלנו בעשורים האחרונים\" - וואלה ספורט", summary: "מכבי חיפה מושפלת: \"אחת הקבוצות החלשות שלנו בעשורים האחרונים\" וואלה ספורט", whyItMatters: "השלכות ביטחוניות שיש לעקוב אחריהן", implications: "השלכות ביטחוניות שיש לעקוב אחריהן", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMiUEFVX3lxTFAxZ3lFRVExaXZBRmoyMk5VbzFTLVIxUTRfUWdQQm1ZNjRHd0U0WlhlX2IyOVpnXzViNnpCYWlnOWpsT3plbi1XZkVJQThFdnZJ?oc=5", sourceName: "וואלה ספורט" },
  { id: 103, type: "content", category: "חברה", title: "רוסיה וסין, מאחוריכן: הטיל ההיפרסוני האמריקני הראשון יוצב מול איראן?", summary: "דיווח בבלומברג\": אחרי שורת עיכובים, ובזמן שליריבות הגדולות יש כבר טילים היפרסוניים מבצעיים, ביקש פיקוד המרכז של צבא ארצות הברית להשתמש בנשר האפל\" מול איראן - למרות שהוא עדיין לא מבצעי לחלוטין. אלו הפרטים", whyItMatters: "נושא חברתי שמשפיע על השיח הציבורי", implications: "נושא חברתי שמשפיע על השיח הציבורי", importance: 6, sourceUrl: "https://www.ynet.co.il/news/article/bkflrvfrwg", sourceName: "ynet" }
];

export const TRENDS: Trend[] = [
  { title: "חיזוק שיתוף הפעולה הביטחוני האזורי", description: "העברת מערכות לייזר לאיחוד האמירויות והפעילות הצבאית נגד רחפנים בלבנון מצביעים על התעצמות שיתופי הפעולה הביטחוניים במזרח התיכון במטרה להתמודד עם איומי איראן.", direction: "up" },
  { title: "עלייה בביקושים לטכנולוגיות בינה מלאכותית וניהול דאטה", description: "גיוסי הון ופעילות חברות בתחום סוכני ה-AI וניהול דאטה מראים על מגמה גוברת של אימוץ פתרונות בינה מלאכותית בארגונים בישראל ובעולם.", direction: "up" },
  { title: "חוסר יציבות ביטחונית וחברתית בישראל", description: "עלייה במספר מקרי האלימות והרצח לצד חקירות פליליות מדגישה את הצורך בשיפור הביטחון הציבורי והטיפול באלימות פנימית.", direction: "up" }
];

export const WINE_NEWS: NewsItem[] = [
  { id: 201, type: "news", category: "יין", title: "New Zealand Wines That Overdeliver—Top Bottles Under $30 - Wine Spectator", summary: "New Zealand Wines That Overdeliver—Top Bottles Under $30 Wine Spectator", whyItMatters: "המלצות על יינות ניו זילנד במחיר נגיש מצביעות על הזדמנויות בשוק היין בישראל, עם ביקוש למוצרים איכותיים במחיר שפוי.", implications: "יבואני יין ישראלים יכולים להרחיב את מגוון היינות ולהתמקד במוצרים עם יחס איכות-מחיר טוב.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMipwFBVV95cUxNQnFla21yUXBCWV83aXdJenNhSTktQ3F3MUQ0RHZvX0gtNUJFMTI4SGhVMmFNbFJvUW5STnpSQmlCTFdGLWpNZ0kxc19uenZtZUJoak8wa3U2Z2dpdm5XNlBnbVdYUnljajcwUEVPNFQ3RFJkYUJ1TGN5Tm01YmdpSmx6RDkyMElVNDhjaWx4Y3J5NWNEN29taVNMSnRQc3dKOFdvX2drUQ?oc=5", sourceName: "Wine Spectator" }
];

export const TOURISM_NEWS: NewsItem[] = [
  { id: 301, type: "news", category: "תיירות", title: "עם \"שטרודל אירוויזוין\" ובית קפה ישראלי: וינה מוכנה לאירוויזיון 2026 - PassportNews", summary: "עם \"שטרודל אירוויזוין\" ובית קפה ישראלי: וינה מוכנה לאירוויזיון 2026 PassportNews", whyItMatters: "הכנות וינה לאירוויזיון 2026 עם נגיעות ישראליות מחזקות את הקשר התרבותי והתיירותי בין ישראל לאירופה.", implications: "צפוי גידול בתיירות ישראלית לאירופה והזדמנויות עסקיות בתחום האירוח והקולינריה.", importance: 7, sourceUrl: "https://news.google.com/rss/articles/CBMiU0FVX3lxTE1EZWd5aURKcE9GLVhwSGxFczItQ3lJOEV6eldxS2c0bW9MeUlMZXhCM3NlUU42a0l5aDZJR0pWWGUtTEt6QzhVRFBaWkdvdFhRb0Q0?oc=5", sourceName: "PassportNews" },
  { id: 302, type: "news", category: "תיירות", title: "דובאי חוזרת למוקד התיירות הישראלי: עלייה בהזמנות וציפייה לחזרת התיירים - PassportNews", summary: "דובאי חוזרת למוקד התיירות הישראלי: עלייה בהזמנות וציפייה לחזרת התיירים PassportNews", whyItMatters: "חזרה של דובאי למוקד התיירות הישראלי מצביעה על חיזוק הקשרים הכלכליים והתיירותיים בין המדינות.", implications: "חברות תיירות ועסקים ישראליים יכולים לנצל את העלייה בהזמנות ולהרחיב פעילות באזור.", importance: 7, sourceUrl: "https://news.google.com/rss/articles/CBMiU0FVX3lxTE84RVRaa0R3N0h5azFmMHV4Yl9UWTdid0RuSWJrZ21Wcnk4UjZCeW51ZWJCeEc3RWZkcFlHZ2RiSTI1aWZBUHNocy1aai1aVEVrZjdF?oc=5", sourceName: "PassportNews" },
  { id: 303, type: "news", category: "תיירות", title: "Golf Your Way Across America with the New Route 66 Golf Trail, Get the Details Here - Travel And Tour World", summary: "Golf Your Way Across America with the New Route 66 Golf Trail, Get the Details Here Travel And Tour World", whyItMatters: "מסלול גולף חדש בארצות הברית מציע הזדמנויות לתיירות נישה, רלוונטי לחברות תיירות ישראליות המתמחות בטיולים יוקרתיים.", implications: "יש מקום לפיתוח חבילות תיירות ייחודיות המשלבות ספורט וטיולים בארה״ב.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMiywFBVV95cUxPT2ZDY1Uyb0htZ2hlUFpSMm5EaTUtS1k2ZUpvRl9udzFMdGRmcFVKRzhpQ19MM3dObE9hTEk3Q1BLc1czSEJIdURrWWtZeEtERlowM3h0RmNMRWR1V095U2I4MlZ0cno5bFcxWE80WnpVbnpoUlR0N3cyNGZKVTFwWjVNZlpJR0dnekpFb1ZkajBvYkFGbWNoMGVUNXpzaGFUQV9zSjg5TlhsT1JPRkhWakJ1LW1mNDdxdFczNUxTNWRqX2tQYjEzOGwzTQ?oc=5", sourceName: "Travel And Tour World" },
  { id: 304, type: "news", category: "תיירות", title: "The Best Ways To Fly to the Seychelles With Points & Miles - Upgraded Points", summary: "The Best Ways To Fly to the Seychelles With Points & Miles Upgraded Points", whyItMatters: "דרכים מומלצות לטוס לסיישל עם נקודות ומיילים מעודדות שימוש במערכות נאמנות, רלוונטי לחברות תעופה ותיירות ישראליות.", implications: "צפוי גידול בביקוש לטיסות יוקרתיות ומנוצלות היטב על ידי לקוחות עם נקודות נאמנות.", importance: 6, sourceUrl: "https://news.google.com/rss/articles/CBMigwFBVV95cUxPNVJxQjFzYVZSWHRCanhhZmVock5MRXI5dnY2b1JZTGtCZnhjOTc0N210YW5lRVNldVZvVHJfaDdnUGFtY2tFSTNxMkU0LWxES3p4SXRzMjV5V1RfNFRVQnpRbnI1NjlSbU1nZWNkZF9mVU9MdGhuT0pPWEtRQkl0QkpEOA?oc=5", sourceName: "Upgraded Points" }
];

export const MARKET_DATA: MarketData = {
  date: NEWS_DATE,
  indices: [
    { name: "תל אביב 125", value: "4,371.32", change: "+0.00%", direction: "stable" },
    { name: "S&P 500", value: "7,250.39", change: "+0.00%", direction: "stable" },
    { name: "נאסדק", value: "25,171", change: "+0.00%", direction: "stable" },
    { name: "דאו גונס", value: "49,665", change: "+0.00%", direction: "stable" }
  ],
  currencies: [
    { name: "דולר/שקל", value: "2.94", change: "+0.00%", direction: "stable" },
    { name: "אירו/שקל", value: "3.45", change: "+0.00%", direction: "stable" },
    { name: "אירו/דולר", value: "1.17", change: "+0.00%", direction: "stable" }
  ],
  commodities: [
    { name: "נפט גולמי", value: "101.61", change: "+0.00%", direction: "stable" },
    { name: "זהב", value: "4,647.70", change: "+0.00%", direction: "stable" },
    { name: "ביטקוין", value: "78,340", change: "+0.00%", direction: "stable" },
    { name: "את'ריום", value: "2,306.51", change: "+0.00%", direction: "stable" },
    { name: "סולנה", value: "84.05", change: "+0.00%", direction: "stable" }
  ],
  israelHeadlines: ["נאסדק עולה ביותר מ-1%, אורקל מזנקת ביותר מ-6%", "מניות הנדל״ן הזניקו את ת״א. זה המדד שננעל בשיא"],
  wallStreetHeadlines: ["Radware lines up 3 investor conferences, with a May 14 webca"],
  watchTomorrow: "",
};
