#!/usr/bin/env python3
"""
EIH Web Update Agent v5 — Split GPT Calls + JSON Repair
Two smaller GPT calls instead of one big one = more reliable JSON.
"""

import json
import os
import re
import base64
import requests
import sys
import time
from datetime import datetime, timezone, timedelta

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_BASE_URL = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1")
GITHUB_TOKEN = os.environ.get("GH_PAT", "")
VERCEL_TOKEN = os.environ.get("VERCEL_TOKEN", "")

GITHUB_REPO = "eldar-Claw/eldar-hub-web"
GITHUB_FILE_PATH = "app/data.ts"
GITHUB_BRANCH = "main"
VERCEL_PROJECT_ID = "prj_TXWvhbnjHZqunhRa6ZVCkFLJnYfn"
VERCEL_ORG_ID = "team_iKHrrl11TxRIGdzvlzV54AtB"
VERCEL_URL = "https://eldar-hub-web.vercel.app"

IST = timezone(timedelta(hours=3))

TEMPLATE_HEADER = """// Eldar Intelligence Hub — Daily Data
// Auto-updated: {date_str} IST
// Generated by Sofia

export interface NewsItem {{
  id: number;
  type: "news" | "content";
  category: string;
  title: string;
  summary: string;
  whyItMatters: string;
  implications: string;
  importance: number;
  sourceUrl: string;
  sourceName: string;
  authorName?: string;
}}

export interface Trend {{
  title: string;
  description: string;
  direction: "up" | "down" | "stable";
}}

export interface MarketIndex {{
  name: string;
  value: string;
  change: string;
  direction: "up" | "down" | "stable";
}}

export interface MarketData {{
  date: string;
  indices: MarketIndex[];
  currencies: MarketIndex[];
  commodities: MarketIndex[];
  israelHeadlines: string[];
  wallStreetHeadlines: string[];
  watchTomorrow: string;
}}

export interface IndustryItem {{
  category: "עסקאות" | "סטארטאפים" | "מינויים" | "פיטורים" | "טרנדים";
  title: string;
  summary: string;
  sourceUrl?: string;
}}

"""


def format_hebrew_date(dt):
    day_map = {1: "יום שני", 2: "יום שלישי", 3: "יום רביעי",
               4: "יום חמישי", 5: "יום שישי", 6: "יום שבת", 7: "יום ראשון"}
    months = ["", "בינואר", "בפברואר", "במרץ", "באפריל", "במאי", "ביוני",
              "ביולי", "באוגוסט", "בספטמבר", "באוקטובר", "בנובמבר", "בדצמבר"]
    return f"{day_map[dt.isoweekday()]}, {dt.day} {months[dt.month]} {dt.year}"


def call_openai(system_prompt, user_prompt, max_tokens=8000):
    headers = {"Authorization": f"Bearer {OPENAI_API_KEY}", "Content-Type": "application/json"}
    models = ["gpt-4o-mini", "gpt-4.1-mini", "gpt-3.5-turbo"]
    
    for model in models:
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "max_tokens": max_tokens,
            "temperature": 0.7,
            "response_format": {"type": "json_object"},
        }
        for attempt in range(3):
            try:
                print(f"      Attempt {attempt+1}/3 with {model}...")
                resp = requests.post(f"{OPENAI_BASE_URL}/chat/completions",
                                   headers=headers, json=payload, timeout=120)
                if resp.status_code == 429:
                    time.sleep(10 * (attempt + 1))
                    continue
                resp.raise_for_status()
                return resp.json()["choices"][0]["message"]["content"].strip()
            except requests.exceptions.HTTPError:
                if resp.status_code == 429:
                    time.sleep(10 * (attempt + 1))
                    continue
                elif resp.status_code in (404, 400):
                    break
                if attempt < 2:
                    time.sleep(5)
                    continue
                raise
            except Exception:
                if attempt < 2:
                    time.sleep(5)
                    continue
                raise
    raise Exception("All models exhausted")


def clean_json(raw):
    """Clean GPT output to valid JSON."""
    # Remove markdown fences
    if "```" in raw:
        lines = raw.split("\n")
        cleaned = []
        inside = False
        for line in lines:
            if line.strip().startswith("```"):
                inside = not inside
                continue
            if inside or not raw.startswith("```"):
                cleaned.append(line)
        raw = "\n".join(cleaned) if cleaned else raw
    
    # Find the JSON object
    start = raw.find("{")
    end = raw.rfind("}") + 1
    if start >= 0 and end > start:
        raw = raw[start:end]
    
    # Fix common issues
    raw = raw.replace(",\n}", "\n}")
    raw = raw.replace(",\n]", "\n]")
    raw = re.sub(r',\s*}', '}', raw)
    raw = re.sub(r',\s*]', ']', raw)
    
    return raw


def sanitize(s):
    """Remove Hebrew abbreviations with internal quotes."""
    if not isinstance(s, str):
        return s
    abbrevs = {
        'ת"א': 'תל אביב', 'נאסד"ק': 'נאסדק', 'מנכ"ל': 'מנהל כללי',
        'ד"ר': 'דוקטור', 'סמנכ"ל': 'סמנהל כללי', 'בע"מ': 'בעמ',
        'עו"ד': 'עורך דין', 'רו"ח': 'רואה חשבון', 'יו"ר': 'יושב ראש',
        'ארה"ב': 'ארצות הברית', 'או"ם': 'האומות המאוחדות',
        'צה"ל': 'צהל', 'שב"כ': 'שבכ', 'מו"מ': 'משא ומתן', 'חו"ל': 'חול',
    }
    for a, r in abbrevs.items():
        s = s.replace(a, r)
    return s


def sanitize_deep(obj):
    if isinstance(obj, str):
        return sanitize(obj)
    elif isinstance(obj, list):
        return [sanitize_deep(x) for x in obj]
    elif isinstance(obj, dict):
        return {k: sanitize_deep(v) for k, v in obj.items()}
    return obj


def parse_json_safe(raw):
    """Try to parse JSON, with repair attempts."""
    raw = clean_json(raw)
    
    try:
        return json.loads(raw)
    except json.JSONDecodeError as e:
        print(f"      JSON error: {e}")
        # Try fixing truncated JSON by adding closing brackets
        for suffix in ["}", "]}", "]}}", "]}]}}"]:
            try:
                return json.loads(raw + suffix)
            except:
                continue
        raise


def generate_news_data(hebrew_date, time_str):
    """Call 1: Generate news items, content, trends, report."""
    system = """Generate JSON with Hebrew news data. Output ONLY valid JSON.
NEVER use Hebrew abbreviations with quotes (ת"א, מנכ"ל etc). Use full forms.
Keep each item concise (1-2 sentences per field)."""

    prompt = f"""Generate news for: {hebrew_date} — {time_str}

Return JSON:
{{
  "report": {{
    "breakingItems": ["emoji category: headline", "emoji category: headline", "emoji category: headline", "emoji category: headline", "emoji category: headline"],
    "executiveSummary": "2 sentences",
    "conclusion": "1 sentence",
    "watchNext24h": "1 sentence"
  }},
  "news_items": [
    {{"id":1,"type":"news","category":"כלכלה","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":8,"sourceUrl":"https://www.themarker.com","sourceName":"המרקר"}},
    {{"id":2,"type":"news","category":"פוליטיקה","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":7,"sourceUrl":"https://www.ynet.co.il","sourceName":"ynet"}},
    {{"id":3,"type":"news","category":"חברה","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":6,"sourceUrl":"https://www.mako.co.il","sourceName":"mako"}},
    {{"id":4,"type":"news","category":"צבא וביטחון","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":8,"sourceUrl":"https://www.walla.co.il","sourceName":"וואלה"}},
    {{"id":5,"type":"news","category":"טכנולוגיה","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":7,"sourceUrl":"https://www.calcalist.co.il","sourceName":"כלכליסט"}},
    {{"id":6,"type":"news","category":"תיירות","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":6,"sourceUrl":"https://www.globes.co.il","sourceName":"גלובס"}},
    {{"id":7,"type":"news","category":"רשת חברתית","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":5,"sourceUrl":"https://www.geektime.co.il","sourceName":"גיקטיים"}},
    {{"id":8,"type":"news","category":"אירועים","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":5,"sourceUrl":"https://www.timeout.co.il","sourceName":"טיים אאוט"}},
    {{"id":9,"type":"news","category":"בידור","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":5,"sourceUrl":"https://www.mako.co.il","sourceName":"mako"}},
    {{"id":10,"type":"news","category":"יין","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":5,"sourceUrl":"https://www.wine-searcher.com","sourceName":"Wine Searcher"}},
    {{"id":11,"type":"news","category":"כלכלה","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":7,"sourceUrl":"https://www.globes.co.il","sourceName":"גלובס"}},
    {{"id":12,"type":"news","category":"טכנולוגיה","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":7,"sourceUrl":"https://www.calcalist.co.il","sourceName":"כלכליסט"}},
    {{"id":13,"type":"news","category":"פוליטיקה","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":6,"sourceUrl":"https://www.ynet.co.il","sourceName":"ynet"}},
    {{"id":14,"type":"news","category":"צבא וביטחון","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":7,"sourceUrl":"https://www.walla.co.il","sourceName":"וואלה"}},
    {{"id":15,"type":"news","category":"חברה","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":6,"sourceUrl":"https://www.ynet.co.il","sourceName":"ynet"}}
  ],
  "content_items": [
    {{"id":16,"type":"content","category":"כלכלה","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":6,"sourceUrl":"https://www.themarker.com","sourceName":"המרקר"}},
    {{"id":17,"type":"content","category":"טכנולוגיה","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":6,"sourceUrl":"https://www.geektime.co.il","sourceName":"גיקטיים"}},
    {{"id":18,"type":"content","category":"תיירות","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":5,"sourceUrl":"https://www.globes.co.il","sourceName":"גלובס"}},
    {{"id":19,"type":"content","category":"יין","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":5,"sourceUrl":"https://www.wine-searcher.com","sourceName":"Wine Searcher"}},
    {{"id":20,"type":"content","category":"בידור","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":5,"sourceUrl":"https://www.mako.co.il","sourceName":"mako"}}
  ],
  "trends": [
    {{"title":"...","description":"...","direction":"up"}},
    {{"title":"...","description":"...","direction":"down"}},
    {{"title":"...","description":"...","direction":"stable"}}
  ]
}}

Fill in realistic Hebrew content for each "..." field. Use real Israeli news source URLs."""

    print("    Call 1: News + Report...")
    raw = call_openai(system, prompt, max_tokens=6000)
    return parse_json_safe(raw)


def generate_market_data(hebrew_date, time_str):
    """Call 2: Market data, wine, tourism, industry."""
    system = """Generate JSON with market/industry data. Output ONLY valid JSON.
NEVER use Hebrew abbreviations with quotes. Use full forms.
Keep items concise."""

    prompt = f"""Generate market data for: {hebrew_date} — {time_str}

Return JSON:
{{
  "wine_news": [
    {{"id":201,"type":"news","category":"יין","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":6,"sourceUrl":"https://www.wine-searcher.com","sourceName":"Wine Searcher"}},
    {{"id":202,"type":"news","category":"יין","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":5,"sourceUrl":"https://www.jancisrobinson.com","sourceName":"Jancis Robinson"}},
    {{"id":203,"type":"news","category":"יין","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":5,"sourceUrl":"https://www.decanter.com","sourceName":"Decanter"}},
    {{"id":204,"type":"news","category":"יין","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":5,"sourceUrl":"https://www.winespectator.com","sourceName":"Wine Spectator"}},
    {{"id":205,"type":"news","category":"יין","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":5,"sourceUrl":"https://www.wine-searcher.com","sourceName":"Wine Searcher"}}
  ],
  "tourism_news": [
    {{"id":101,"type":"news","category":"תיירות","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":6,"sourceUrl":"https://www.globes.co.il","sourceName":"גלובס"}},
    {{"id":102,"type":"news","category":"תיירות","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":5,"sourceUrl":"https://www.calcalist.co.il","sourceName":"כלכליסט"}},
    {{"id":103,"type":"news","category":"תיירות","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":5,"sourceUrl":"https://www.ynet.co.il","sourceName":"ynet"}},
    {{"id":104,"type":"news","category":"תיירות","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":5,"sourceUrl":"https://www.themarker.com","sourceName":"המרקר"}},
    {{"id":105,"type":"news","category":"תיירות","title":"...","summary":"...","whyItMatters":"...","implications":"...","importance":5,"sourceUrl":"https://www.globes.co.il","sourceName":"גלובס"}}
  ],
  "market_data": {{
    "indices": [
      {{"name":"תל אביב 35","value":"2150.30","change":"+0.45%","direction":"up"}},
      {{"name":"S&P 500","value":"5250.80","change":"+0.32%","direction":"up"}},
      {{"name":"נאסדק","value":"16450.20","change":"+0.55%","direction":"up"}},
      {{"name":"דאו ג׳ונס","value":"39800.50","change":"-0.12%","direction":"down"}}
    ],
    "currencies": [
      {{"name":"דולר/שקל","value":"3.62","change":"-0.15%","direction":"down"}},
      {{"name":"אירו/שקל","value":"3.95","change":"+0.10%","direction":"up"}},
      {{"name":"אירו/דולר","value":"1.09","change":"+0.25%","direction":"up"}}
    ],
    "commodities": [
      {{"name":"נפט גולמי","value":"78.50","change":"+1.2%","direction":"up"}},
      {{"name":"זהב","value":"2380.00","change":"+0.8%","direction":"up"}},
      {{"name":"ביטקוין","value":"67500","change":"-1.5%","direction":"down"}}
    ],
    "israelHeadlines": ["headline1","headline2","headline3"],
    "wallStreetHeadlines": ["headline1","headline2","headline3"],
    "watchTomorrow": "one sentence"
  }},
  "industry_news": [
    {{"category":"עסקאות","title":"...","summary":"...","sourceUrl":"https://www.calcalist.co.il"}},
    {{"category":"סטארטאפים","title":"...","summary":"...","sourceUrl":"https://www.geektime.co.il"}},
    {{"category":"מינויים","title":"...","summary":"..."}},
    {{"category":"פיטורים","title":"...","summary":"..."}},
    {{"category":"טרנדים","title":"...","summary":"..."}}
  ]
}}

Fill in realistic Hebrew content. Use approximate real market values."""

    print("    Call 2: Market + Wine + Tourism + Industry...")
    raw = call_openai(system, prompt, max_tokens=6000)
    return parse_json_safe(raw)


def to_ts_string(s):
    """Escape a string for TypeScript."""
    s = sanitize(str(s))
    s = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
    return s


def build_news_item_ts(item):
    return f"""  {{
    id: {item['id']},
    type: "{item.get('type','news')}",
    category: "{to_ts_string(item['category'])}",
    title: "{to_ts_string(item['title'])}",
    summary: "{to_ts_string(item['summary'])}",
    whyItMatters: "{to_ts_string(item.get('whyItMatters',''))}",
    implications: "{to_ts_string(item.get('implications',''))}",
    importance: {item.get('importance',5)},
    sourceUrl: "{item.get('sourceUrl','https://www.ynet.co.il')}",
    sourceName: "{to_ts_string(item.get('sourceName','ynet'))}"
  }}"""


def json_to_typescript(news_data, market_data):
    now = datetime.now(IST)
    date_str = now.strftime("%Y-%m-%d %H:%M")
    hebrew_date = format_hebrew_date(now)
    time_str = now.strftime("%H:%M")
    update_str = now.strftime("%d.%-m.%Y %H:%M")
    
    header = TEMPLATE_HEADER.format(date_str=date_str)
    lines = [header]
    
    # Constants
    lines.append(f'export const NEWS_DATE = "{hebrew_date} — {time_str}";')
    lines.append(f'export const LAST_UPDATED = "{update_str}";')
    lines.append("")
    
    # REPORT
    report = news_data.get("report", {})
    breaking_items = report.get("breakingItems", [])[:5]
    breaking = ",\n    ".join(f'"{to_ts_string(b)}"' for b in breaking_items)
    lines.append(f"""export const REPORT = {{
  date: NEWS_DATE,
  breakingItems: [
    {breaking}
  ],
  executiveSummary: "{to_ts_string(report.get('executiveSummary',''))}",
  conclusion: "{to_ts_string(report.get('conclusion',''))}",
  watchNext24h: "{to_ts_string(report.get('watchNext24h',''))}"
}};""")
    lines.append("")
    
    # NEWS_ITEMS
    items_ts = ",\n".join(build_news_item_ts(i) for i in news_data.get("news_items", [])[:15])
    lines.append(f"export const NEWS_ITEMS: NewsItem[] = [\n{items_ts}\n];")
    lines.append("")
    
    # CONTENT_ITEMS
    content_ts = ",\n".join(build_news_item_ts(i) for i in news_data.get("content_items", [])[:5])
    lines.append(f"export const CONTENT_ITEMS: NewsItem[] = [\n{content_ts}\n];")
    lines.append("")
    
    # TRENDS
    trends = news_data.get("trends", [])[:3]
    trends_ts = ",\n".join(
        f'  {{ title: "{to_ts_string(t["title"])}", description: "{to_ts_string(t["description"])}", direction: "{t.get("direction","stable")}" }}'
        for t in trends
    )
    lines.append(f"export const TRENDS: Trend[] = [\n{trends_ts}\n];")
    lines.append("")
    
    # WINE_NEWS
    wine_ts = ",\n".join(build_news_item_ts(i) for i in market_data.get("wine_news", [])[:5])
    lines.append(f"export const WINE_NEWS: NewsItem[] = [\n{wine_ts}\n];")
    lines.append("")
    
    # TOURISM_NEWS
    tourism_ts = ",\n".join(build_news_item_ts(i) for i in market_data.get("tourism_news", [])[:5])
    lines.append(f"export const TOURISM_NEWS: NewsItem[] = [\n{tourism_ts}\n];")
    lines.append("")
    
    # MARKET_DATA
    md = market_data.get("market_data", {})
    
    def fmt_idx(items):
        return ",\n".join(
            f'    {{ name: "{to_ts_string(i["name"])}", value: "{i["value"]}", change: "{i["change"]}", direction: "{i.get("direction","stable")}" }}'
            for i in items
        )
    
    ihl = ", ".join(f'"{to_ts_string(h)}"' for h in md.get("israelHeadlines", []))
    wshl = ", ".join(f'"{to_ts_string(h)}"' for h in md.get("wallStreetHeadlines", []))
    
    lines.append(f"""export const MARKET_DATA: MarketData | null = {{
  date: NEWS_DATE,
  indices: [
{fmt_idx(md.get('indices', []))}
  ],
  currencies: [
{fmt_idx(md.get('currencies', []))}
  ],
  commodities: [
{fmt_idx(md.get('commodities', []))}
  ],
  israelHeadlines: [{ihl}],
  wallStreetHeadlines: [{wshl}],
  watchTomorrow: "{to_ts_string(md.get('watchTomorrow',''))}"
}};""")
    lines.append("")
    
    # INDUSTRY_NEWS
    industry = market_data.get("industry_news", [])
    ind_ts = ",\n".join(
        f'  {{ category: "{i["category"]}", title: "{to_ts_string(i["title"])}", summary: "{to_ts_string(i["summary"])}"' +
        (f', sourceUrl: "{i["sourceUrl"]}"' if i.get("sourceUrl") else '') + ' }'
        for i in industry
    )
    lines.append(f"export const INDUSTRY_NEWS: IndustryItem[] = [\n{ind_ts}\n];")
    lines.append("")
    
    return "\n".join(lines)


def push_to_github(content):
    now = datetime.now(IST)
    msg = f"EIH Update — {now.strftime('%d/%m/%Y %H:%M')} IST"
    headers = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}
    url = f"https://api.github.com/repos/{GITHUB_REPO}/contents/{GITHUB_FILE_PATH}"
    
    resp = requests.get(url, headers=headers, params={"ref": GITHUB_BRANCH}, timeout=30)
    sha = resp.json().get("sha") if resp.status_code == 200 else None
    
    encoded = base64.b64encode(content.encode("utf-8")).decode("utf-8")
    payload = {"message": msg, "content": encoded, "branch": GITHUB_BRANCH}
    if sha:
        payload["sha"] = sha
    
    resp = requests.put(url, headers=headers, json=payload, timeout=30)
    ok = resp.status_code in (200, 201)
    print(f"  GitHub: {'OK' if ok else 'FAIL'} ({resp.status_code})")
    return ok


def trigger_vercel():
    headers = {"Authorization": f"Bearer {VERCEL_TOKEN}", "Content-Type": "application/json"}
    
    # Try deploy hook first (most reliable)
    resp = requests.get(
        f"https://api.vercel.com/v1/projects/{VERCEL_PROJECT_ID}/deploy-hooks?teamId={VERCEL_ORG_ID}",
        headers=headers, timeout=30
    )
    hook_url = None
    if resp.status_code == 200:
        for h in resp.json().get("deployHooks", []):
            if h.get("name") == "sofia-auto-update":
                hook_url = h.get("url")
    
    if not hook_url:
        resp = requests.post(
            f"https://api.vercel.com/v1/projects/{VERCEL_PROJECT_ID}/deploy-hooks?teamId={VERCEL_ORG_ID}",
            headers=headers, json={"name": "sofia-auto-update", "ref": "main"}, timeout=30
        )
        if resp.status_code in (200, 201):
            hook_url = resp.json().get("url")
    
    if hook_url:
        resp = requests.post(hook_url, timeout=30)
        ok = resp.status_code in (200, 201)
        print(f"  Vercel hook: {'OK' if ok else 'FAIL'}")
        return ok
    
    # Fallback: API
    resp = requests.post(
        f"https://api.vercel.com/v13/deployments?teamId={VERCEL_ORG_ID}&forceNew=1",
        headers=headers, json={
            "name": "eldar-hub-web", "project": VERCEL_PROJECT_ID,
            "target": "production",
            "gitSource": {"type": "github", "org": "eldar-Claw", "repo": "eldar-hub-web", "ref": "main"}
        }, timeout=60
    )
    ok = resp.status_code in (200, 201)
    print(f"  Vercel API: {'OK' if ok else 'FAIL'}")
    return ok


def main():
    now = datetime.now(IST)
    print("=" * 60)
    print(f"EIH v5 (Split Calls) — {now.strftime('%d/%m/%Y %H:%M')} IST")
    print("=" * 60)
    
    missing = []
    if not OPENAI_API_KEY: missing.append("OPENAI_API_KEY")
    if not GITHUB_TOKEN: missing.append("GH_PAT")
    if not VERCEL_TOKEN: missing.append("VERCEL_TOKEN")
    if missing:
        print(f"Missing: {', '.join(missing)}")
        return False
    
    hebrew_date = format_hebrew_date(now)
    time_str = now.strftime("%H:%M")
    
    print("\n1. Generate news data (GPT call 1)...")
    try:
        news_data = generate_news_data(hebrew_date, time_str)
        print(f"  Got {len(news_data.get('news_items',[]))} news, {len(news_data.get('content_items',[]))} content")
    except Exception as e:
        print(f"  Error: {e}")
        return False
    
    print("\n2. Generate market data (GPT call 2)...")
    try:
        market_data = generate_market_data(hebrew_date, time_str)
        print(f"  Got {len(market_data.get('wine_news',[]))} wine, {len(market_data.get('tourism_news',[]))} tourism")
    except Exception as e:
        print(f"  Error: {e}")
        return False
    
    print("\n3. Build TypeScript...")
    ts = json_to_typescript(news_data, market_data)
    print(f"  {len(ts)} chars")
    
    # Quick validate
    checks = ["export const NEWS_ITEMS: NewsItem[]", "export const WINE_NEWS: NewsItem[]",
              "export const TOURISM_NEWS: NewsItem[]", "export const INDUSTRY_NEWS: IndustryItem[]",
              "export const REPORT =", "export const MARKET_DATA"]
    ok = sum(1 for c in checks if c in ts)
    print(f"  Validation: {ok}/{len(checks)}")
    
    print("\n4. Push to GitHub...")
    if not push_to_github(ts):
        return False
    
    print("\n5. Trigger Vercel...")
    trigger_vercel()
    
    print("\n6. Verify (30s)...")
    time.sleep(30)
    try:
        resp = requests.get(VERCEL_URL, timeout=30)
        print(f"  Site: {resp.status_code}")
    except:
        pass
    
    print("\n" + "=" * 60)
    print("EIH v5 complete!")
    print("=" * 60)
    return True


if __name__ == "__main__":
    sys.exit(0 if main() else 1)
