#!/usr/bin/env python3
"""
EIH Web Update Agent v4 — Template-Based
Interfaces are FIXED (hardcoded). GPT only generates JSON data.
This guarantees TypeScript compilation always succeeds.
"""

import json
import os
import re
import base64
import requests
import sys
import time
from datetime import datetime, timezone, timedelta

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_BASE_URL = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1")
GITHUB_TOKEN = os.environ.get("GH_PAT", "")
VERCEL_TOKEN = os.environ.get("VERCEL_TOKEN", "")

GITHUB_REPO = "eldar-Claw/eldar-hub-web"
GITHUB_FILE_PATH = "app/data.ts"
GITHUB_BRANCH = "main"
VERCEL_PROJECT_ID = "prj_TXWvhbnjHZqunhRa6ZVCkFLJnYfn"
VERCEL_ORG_ID = "team_iKHrrl11TxRIGdzvlzV54AtB"
VERCEL_URL = "https://eldar-hub-web.vercel.app"

IST = timezone(timedelta(hours=3))

# ============================================================
# FIXED TEMPLATE — these interfaces NEVER change
# ============================================================
TEMPLATE_HEADER = """// Eldar Intelligence Hub — Daily Data
// Auto-updated: {date_str} IST
// Generated by Sofia

export interface NewsItem {{
  id: number;
  type: "news" | "content";
  category: string;
  title: string;
  summary: string;
  whyItMatters: string;
  implications: string;
  importance: number;
  sourceUrl: string;
  sourceName: string;
  authorName?: string;
}}

export interface Trend {{
  title: string;
  description: string;
  direction: "up" | "down" | "stable";
}}

export interface MarketIndex {{
  name: string;
  value: string;
  change: string;
  direction: "up" | "down" | "stable";
}}

export interface MarketData {{
  date: string;
  indices: MarketIndex[];
  currencies: MarketIndex[];
  commodities: MarketIndex[];
  israelHeadlines: string[];
  wallStreetHeadlines: string[];
  watchTomorrow: string;
}}

export interface IndustryItem {{
  category: "עסקאות" | "סטארטאפים" | "מינויים" | "פיטורים" | "טרנדים";
  title: string;
  summary: string;
  sourceUrl?: string;
}}

"""


def format_hebrew_date(dt):
    day_map = {1: "יום שני", 2: "יום שלישי", 3: "יום רביעי",
               4: "יום חמישי", 5: "יום שישי", 6: "יום שבת", 7: "יום ראשון"}
    months = ["", "בינואר", "בפברואר", "במרץ", "באפריל", "במאי", "ביוני",
              "ביולי", "באוגוסט", "בספטמבר", "באוקטובר", "בנובמבר", "בדצמבר"]
    return f"{day_map[dt.isoweekday()]}, {dt.day} {months[dt.month]} {dt.year}"


def call_openai(system_prompt, user_prompt):
    headers = {"Authorization": f"Bearer {OPENAI_API_KEY}", "Content-Type": "application/json"}
    models = ["gpt-4o-mini", "gpt-4.1-mini", "gpt-3.5-turbo"]
    
    for model in models:
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "max_tokens": 12000,
            "temperature": 0.7,
        }
        for attempt in range(3):
            try:
                print(f"    Attempt {attempt+1}/3 with {model}...")
                resp = requests.post(f"{OPENAI_BASE_URL}/chat/completions",
                                   headers=headers, json=payload, timeout=180)
                if resp.status_code == 429:
                    time.sleep(10 * (attempt + 1))
                    continue
                resp.raise_for_status()
                return resp.json()["choices"][0]["message"]["content"].strip()
            except requests.exceptions.HTTPError:
                if resp.status_code == 429:
                    time.sleep(10 * (attempt + 1))
                    continue
                elif resp.status_code in (404, 400):
                    break
                if attempt < 2:
                    time.sleep(5)
                    continue
                raise
            except Exception:
                if attempt < 2:
                    time.sleep(5)
                    continue
                raise
    raise Exception("All models exhausted")


def sanitize_string(s):
    """Remove unescaped double quotes from Hebrew strings."""
    abbrevs = {
        'ת"א': 'תל אביב', 'נאסד"ק': 'נאסדק', 'מנכ"ל': 'מנהל כללי',
        'ד"ר': 'דוקטור', 'סמנכ"ל': 'סמנהל כללי', 'בע"מ': 'בעמ',
        'עו"ד': 'עורך דין', 'רו"ח': 'רואה חשבון', 'יו"ר': 'יושב ראש',
        'ארה"ב': 'ארצות הברית', 'או"ם': 'האומות המאוחדות',
        'צה"ל': 'צהל', 'שב"כ': 'שבכ', 'מו"מ': 'משא ומתן', 'חו"ל': 'חול',
    }
    for abbr, repl in abbrevs.items():
        s = s.replace(abbr, repl)
    # Remove any remaining internal double quotes
    s = s.replace('"', "'")
    return s


def sanitize_json(data):
    """Recursively sanitize all strings in JSON data."""
    if isinstance(data, str):
        return sanitize_string(data)
    elif isinstance(data, list):
        return [sanitize_json(item) for item in data]
    elif isinstance(data, dict):
        return {k: sanitize_json(v) for k, v in data.items()}
    return data


def generate_json_data():
    """Ask GPT to generate ONLY the data as JSON — no TypeScript."""
    now = datetime.now(IST)
    hebrew_date = format_hebrew_date(now)
    time_str = now.strftime("%H:%M")
    update_str = now.strftime("%d.%-m.%Y %H:%M")

    system_prompt = """You generate news data for the Eldar Intelligence Hub in JSON format.
Output ONLY valid JSON. No markdown. No explanations. No code fences.

All text content must be in Hebrew.
NEVER use Hebrew abbreviations with internal quotes (like ת"א, מנכ"ל, ד"ר, ארה"ב, צה"ל, נאסד"ק).
Instead write the full form: תל אביב, מנהל כללי, דוקטור, ארצות הברית, צהל, נאסדק.

Generate REALISTIC news based on current events."""

    user_prompt = f"""Generate JSON data for date: {hebrew_date} — {time_str}

Return a single JSON object with these keys:

{{
  "news_date": "{hebrew_date} — {time_str}",
  "last_updated": "{update_str}",
  "report": {{
    "breakingItems": ["emoji category: headline", ...5 items],
    "executiveSummary": "2-3 sentence summary",
    "conclusion": "1-2 sentence conclusion",
    "watchNext24h": "what to watch"
  }},
  "news_items": [
    {{
      "id": 1, "type": "news", "category": "כלכלה",
      "title": "...", "summary": "...", "whyItMatters": "...", "implications": "...",
      "importance": 8, "sourceUrl": "https://...", "sourceName": "..."
    }},
    ...15 items total
  ],
  "content_items": [...5 items, same format as news_items but with type: "content", ids 16-20],
  "trends": [
    {{"title": "...", "description": "...", "direction": "up|down|stable"}},
    ...3 items
  ],
  "wine_news": [...5 items, same format as news_items, all category: "יין", ids 201-205],
  "tourism_news": [...5 items, same format as news_items, all category: "תיירות", ids 101-105],
  "market_data": {{
    "indices": [{{"name": "S&P 500", "value": "4200.50", "change": "+0.75%", "direction": "up"}}, ...4 indices],
    "currencies": [{{"name": "דולר", "value": "3.60", "change": "-0.2%", "direction": "down"}}, ...3 currencies],
    "commodities": [{{"name": "נפט", "value": "75.00", "change": "+1.5%", "direction": "up"}}, ...3 commodities],
    "israelHeadlines": ["headline1", "headline2", "headline3"],
    "wallStreetHeadlines": ["headline1", "headline2", "headline3"],
    "watchTomorrow": "what to watch"
  }},
  "industry_news": [
    {{"category": "עסקאות", "title": "...", "summary": "...", "sourceUrl": "https://..."}},
    {{"category": "סטארטאפים", "title": "...", "summary": "..."}},
    {{"category": "מינויים", "title": "...", "summary": "..."}},
    {{"category": "פיטורים", "title": "...", "summary": "..."}},
    {{"category": "טרנדים", "title": "...", "summary": "..."}}
  ]
}}

NEWS_ITEMS MUST include at least 1 from EACH category:
כלכלה, פוליטיקה, חברה, צבא וביטחון, טכנולוגיה, תיירות, רשת חברתית, אירועים, בידור, יין

breakingItems format: "emoji category: headline text"
Example: "💰 כלכלה: בנק ישראל מעלה ריבית"

Use emojis: 💰=כלכלה, 🗳️=פוליטיקה, 👥=חברה, 🛡️=צבא, 💻=טכנולוגיה, ✈️=תיירות, 📱=רשת חברתית, 📅=אירועים, 🎬=בידור, 🍷=יין

Output ONLY the JSON object."""

    print("  Calling GPT for JSON data...")
    raw = call_openai(system_prompt, user_prompt)
    
    # Clean markdown fences
    if raw.startswith("```"):
        lines = raw.split("\n")
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines[-1].strip() == "```":
            lines = lines[:-1]
        raw = "\n".join(lines)
    
    data = json.loads(raw)
    data = sanitize_json(data)
    return data


def json_to_typescript(data):
    """Convert JSON data to TypeScript using the fixed template."""
    now = datetime.now(IST)
    date_str = now.strftime("%Y-%m-%d %H:%M")
    
    header = TEMPLATE_HEADER.format(date_str=date_str)
    
    lines = [header]
    
    # NEWS_DATE and LAST_UPDATED
    lines.append(f'export const NEWS_DATE = "{data["news_date"]}";')
    lines.append(f'export const LAST_UPDATED = "{data["last_updated"]}";')
    lines.append("")
    
    # REPORT
    report = data["report"]
    breaking = ",\n    ".join(f'"{item}"' for item in report["breakingItems"][:5])
    lines.append(f"""export const REPORT = {{
  date: NEWS_DATE,
  breakingItems: [
    {breaking}
  ],
  executiveSummary: "{report['executiveSummary']}",
  conclusion: "{report['conclusion']}",
  watchNext24h: "{report['watchNext24h']}"
}};""")
    lines.append("")
    
    # NEWS_ITEMS
    lines.append("export const NEWS_ITEMS: NewsItem[] = [")
    for item in data["news_items"][:15]:
        lines.append(f"""  {{
    id: {item['id']},
    type: "{item.get('type', 'news')}",
    category: "{item['category']}",
    title: "{item['title']}",
    summary: "{item['summary']}",
    whyItMatters: "{item.get('whyItMatters', '')}",
    implications: "{item.get('implications', '')}",
    importance: {item.get('importance', 5)},
    sourceUrl: "{item.get('sourceUrl', 'https://www.ynet.co.il')}",
    sourceName: "{item.get('sourceName', 'ynet')}"
  }},""")
    lines.append("];")
    lines.append("")
    
    # CONTENT_ITEMS
    lines.append("export const CONTENT_ITEMS: NewsItem[] = [")
    for item in data.get("content_items", [])[:5]:
        lines.append(f"""  {{
    id: {item['id']},
    type: "{item.get('type', 'content')}",
    category: "{item['category']}",
    title: "{item['title']}",
    summary: "{item['summary']}",
    whyItMatters: "{item.get('whyItMatters', '')}",
    implications: "{item.get('implications', '')}",
    importance: {item.get('importance', 5)},
    sourceUrl: "{item.get('sourceUrl', 'https://www.ynet.co.il')}",
    sourceName: "{item.get('sourceName', 'ynet')}"
  }},""")
    lines.append("];")
    lines.append("")
    
    # TRENDS
    lines.append("export const TRENDS: Trend[] = [")
    for t in data.get("trends", [])[:3]:
        lines.append(f"""  {{
    title: "{t['title']}",
    description: "{t['description']}",
    direction: "{t.get('direction', 'stable')}"
  }},""")
    lines.append("];")
    lines.append("")
    
    # WINE_NEWS
    lines.append("export const WINE_NEWS: NewsItem[] = [")
    for item in data.get("wine_news", [])[:5]:
        lines.append(f"""  {{
    id: {item['id']},
    type: "{item.get('type', 'news')}",
    category: "יין",
    title: "{item['title']}",
    summary: "{item['summary']}",
    whyItMatters: "{item.get('whyItMatters', 'חשוב למעקב אחר שוק היין')}",
    implications: "{item.get('implications', 'השפעה על שוק היין')}",
    importance: {item.get('importance', 5)},
    sourceUrl: "{item.get('sourceUrl', 'https://www.wine-searcher.com')}",
    sourceName: "{item.get('sourceName', 'Wine Searcher')}"
  }},""")
    lines.append("];")
    lines.append("")
    
    # TOURISM_NEWS
    lines.append("export const TOURISM_NEWS: NewsItem[] = [")
    for item in data.get("tourism_news", [])[:5]:
        lines.append(f"""  {{
    id: {item['id']},
    type: "{item.get('type', 'news')}",
    category: "תיירות",
    title: "{item['title']}",
    summary: "{item['summary']}",
    whyItMatters: "{item.get('whyItMatters', 'חשוב למעקב אחר מגמות התיירות')}",
    implications: "{item.get('implications', 'השפעה על ענף התיירות')}",
    importance: {item.get('importance', 5)},
    sourceUrl: "{item.get('sourceUrl', 'https://www.globes.co.il')}",
    sourceName: "{item.get('sourceName', 'גלובס')}"
  }},""")
    lines.append("];")
    lines.append("")
    
    # MARKET_DATA
    md = data.get("market_data", {})
    
    def format_indices(indices):
        parts = []
        for idx in indices:
            parts.append(f'    {{ name: "{idx["name"]}", value: "{idx["value"]}", change: "{idx["change"]}", direction: "{idx.get("direction", "stable")}" }}')
        return ",\n".join(parts)
    
    israel_hl = ", ".join(f'"{h}"' for h in md.get("israelHeadlines", []))
    ws_hl = ", ".join(f'"{h}"' for h in md.get("wallStreetHeadlines", []))
    
    lines.append(f"""export const MARKET_DATA: MarketData | null = {{
  date: NEWS_DATE,
  indices: [
{format_indices(md.get('indices', []))}
  ],
  currencies: [
{format_indices(md.get('currencies', []))}
  ],
  commodities: [
{format_indices(md.get('commodities', []))}
  ],
  israelHeadlines: [{israel_hl}],
  wallStreetHeadlines: [{ws_hl}],
  watchTomorrow: "{md.get('watchTomorrow', '')}"
}};""")
    lines.append("")
    
    # INDUSTRY_NEWS
    lines.append("export const INDUSTRY_NEWS: IndustryItem[] = [")
    for item in data.get("industry_news", []):
        src = f'\n    sourceUrl: "{item["sourceUrl"]}",' if item.get("sourceUrl") else ""
        lines.append(f"""  {{
    category: "{item['category']}",
    title: "{item['title']}",
    summary: "{item['summary']}",{src}
  }},""")
    lines.append("];")
    lines.append("")
    
    return "\n".join(lines)


def push_to_github(content, commit_message=None):
    if not commit_message:
        now = datetime.now(IST)
        commit_message = f"EIH Update — {now.strftime('%d/%m/%Y %H:%M')} IST"
    
    headers = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}
    url = f"https://api.github.com/repos/{GITHUB_REPO}/contents/{GITHUB_FILE_PATH}"
    
    resp = requests.get(url, headers=headers, params={"ref": GITHUB_BRANCH}, timeout=30)
    sha = resp.json()["sha"] if resp.status_code == 200 else None
    
    encoded = base64.b64encode(content.encode("utf-8")).decode("utf-8")
    payload = {"message": commit_message, "content": encoded, "branch": GITHUB_BRANCH}
    if sha:
        payload["sha"] = sha
    
    resp = requests.put(url, headers=headers, json=payload, timeout=30)
    if resp.status_code in (200, 201):
        print(f"  GitHub push OK! SHA: {resp.json()['content']['sha'][:12]}")
        return True
    print(f"  GitHub push FAILED: {resp.status_code}")
    return False


def trigger_vercel_deploy():
    headers = {"Authorization": f"Bearer {VERCEL_TOKEN}", "Content-Type": "application/json"}
    
    # Try API deploy
    resp = requests.post(
        f"https://api.vercel.com/v13/deployments?teamId={VERCEL_ORG_ID}&forceNew=1",
        headers=headers, json={
            "name": "eldar-hub-web", "project": VERCEL_PROJECT_ID,
            "target": "production",
            "gitSource": {"type": "github", "org": "eldar-Claw", "repo": "eldar-hub-web", "ref": "main"}
        }, timeout=60
    )
    
    if resp.status_code in (200, 201):
        print(f"  Vercel deploy triggered!")
        return True
    
    # Fallback: deploy hook
    resp = requests.get(
        f"https://api.vercel.com/v1/projects/{VERCEL_PROJECT_ID}/deploy-hooks?teamId={VERCEL_ORG_ID}",
        headers=headers, timeout=30
    )
    hook_url = None
    if resp.status_code == 200:
        for h in resp.json().get("deployHooks", []):
            if h.get("name") == "sofia-auto-update":
                hook_url = h.get("url")
    if not hook_url:
        resp = requests.post(
            f"https://api.vercel.com/v1/projects/{VERCEL_PROJECT_ID}/deploy-hooks?teamId={VERCEL_ORG_ID}",
            headers=headers, json={"name": "sofia-auto-update", "ref": "main"}, timeout=30
        )
        if resp.status_code in (200, 201):
            hook_url = resp.json().get("url")
    if hook_url:
        resp = requests.post(hook_url, timeout=30)
        if resp.status_code in (200, 201):
            print("  Deploy hook triggered!")
            return True
    
    print("  Deploy failed")
    return False


def main():
    now = datetime.now(IST)
    print("=" * 60)
    print(f"EIH Web Update v4 (Template) — {now.strftime('%d/%m/%Y %H:%M')} IST")
    print("=" * 60)
    
    missing = []
    if not OPENAI_API_KEY: missing.append("OPENAI_API_KEY")
    if not GITHUB_TOKEN: missing.append("GH_PAT")
    if not VERCEL_TOKEN: missing.append("VERCEL_TOKEN")
    if missing:
        print(f"Missing: {', '.join(missing)}")
        return False
    
    print("\n1. Generate JSON data...")
    try:
        data = generate_json_data()
        print(f"  Got {len(data.get('news_items', []))} news items")
    except json.JSONDecodeError as e:
        print(f"  JSON parse error: {e}")
        return False
    except Exception as e:
        print(f"  Error: {e}")
        return False
    
    print("\n2. Convert to TypeScript...")
    ts_content = json_to_typescript(data)
    print(f"  Generated {len(ts_content)} chars")
    
    # Validate
    required = ["export const NEWS_ITEMS", "export const WINE_NEWS: NewsItem[]",
                "export const TOURISM_NEWS: NewsItem[]", "export const INDUSTRY_NEWS: IndustryItem[]",
                "export const REPORT =", "export const MARKET_DATA"]
    ok = all(r in ts_content for r in required)
    print(f"  Validation: {'PASS' if ok else 'FAIL'}")
    if not ok:
        for r in required:
            if r not in ts_content:
                print(f"    MISSING: {r}")
    
    print("\n3. Push to GitHub...")
    if not push_to_github(ts_content):
        return False
    
    print("\n4. Trigger Vercel deploy...")
    trigger_vercel_deploy()
    
    print("\n5. Waiting 30s and verifying...")
    time.sleep(30)
    try:
        resp = requests.get(VERCEL_URL, timeout=30)
        print(f"  Site status: {resp.status_code}")
    except:
        print("  Could not verify")
    
    print("\n" + "=" * 60)
    print("Done!")
    print("=" * 60)
    return True


if __name__ == "__main__":
    sys.exit(0 if main() else 1)
